export default DATA = {
    'current_page': 1,
    'total_count': 2768,
    'total_pages': 56,
    'data': [
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159932.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159932@@@@@6A949982@@@@@@MMJ',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'MMJ',
            'tag': '[\'DailyShareBuy-BackNotice\']',
            'title': 'Daily share buy-back notice - Appendix 3E',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:33:13Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159931.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159931@@@@@3A526548@@@@@@IDT',
            'page_count': 6,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'IDT',
            'tag': '[\'Changeinsubstantialholding\']',
            'title': 'Change in substantial holding',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:26:38Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159930.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159930@@@@@6A949979@@@@@@SGC',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'SGC',
            'tag': '[\'ChangeofDirector’sInterestNotice\']',
            'title': 'Appendix 3Y - G Channon',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:15:08Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159929.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159929@@@@@6A949978@@@@@@SGC',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'SGC',
            'tag': '[\'ChangeofDirector’sInterestNotice\']',
            'title': 'Appendix 3Y - G Jeffery',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:14:33Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159928.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159928@@@@@6A949977@@@@@@SGC',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'SGC',
            'tag': '[\'ChangeofDirector’sInterestNotice\']',
            'title': 'Appendix 3Y - A Childs',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:13:18Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159927.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159927@@@@@6A949976@@@@@@SGC',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'SGC',
            'tag': '[\'CleansingNotice\']',
            'title': 'S708A Notice',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:12:33Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159926.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159926@@@@@6A949975@@@@@@SGC',
            'page_count': 12,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'SGC',
            'tag': '[\'Appendix3B\']',
            'title': 'Appendix 3B',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:10:53Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159925.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159925@@@@@2A1180173@@@@@@ORG',
            'page_count': 9,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'ORG',
            'tag': '[\'Appendix3B\']',
            'title': 'Appendix 3B',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T07:03:23Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159924.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159924@@@@@6A949974@@@@@@MOD',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'MOD',
            'tag': '[\'Ceasingtobeasubstantialholder\']',
            'title': 'Ceasing to be a substantial holder',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:59:18Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159923.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159923@@@@@2A1180172@@@@@@TGA',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'TGA',
            'tag': '[\'Ceasingtobeasubstantialholder\']',
            'title': 'Ceasing to be a substantial holder',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:57:33Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159922.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159922@@@@@2A1180171@@@@@@ORG',
            'page_count': 35,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'ORG',
            'tag': '[\'Constitution\']',
            'title': 'Amendment of Constitution',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:55:13Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159921.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159921@@@@@2A1180170@@@@@@WBA',
            'page_count': 3,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'WBA',
            'tag': '[\'ChangeofDirector’sInterestNotice\']',
            'title': 'Appendix 3Y',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:54:23Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159920.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159920@@@@@6A949973@@@@@@RCE',
            'page_count': 3,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'RCE',
            'tag': '[\'Changeinsubstantialholding\']',
            'title': 'Change in substantial holding',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:53:43Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159919.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159919@@@@@2A1180169@@@@@@TGM',
            'page_count': 19,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'TGM',
            'tag': '[\'NoticeofAnnualGeneralMeeting\',\'ProxyForm\']',
            'title': 'Notice of Annual General Meeting/Proxy Form',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:53:08Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159918.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159918@@@@@3A526547@@@@@@TRS',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'TRS',
            'tag': '[\'ResultsofMeeting\']',
            'title': 'Results of Meeting',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:47:13Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159917.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159917@@@@@2A1180168@@@@@@ORG',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'ORG',
            'tag': '[\'ResultsofMeeting\']',
            'title': 'Origin Energy Annual General Meeting Results 2019',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:41:33Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159916.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159916@@@@@2A1180167@@@@@@HVN',
            'page_count': 15,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'HVN',
            'tag': '[\'NoticeofAnnualGeneralMeeting\',\'ProxyForm\']',
            'title': '2019 Notice of Meeting - correction',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:40:48Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159915.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159915@@@@@6A949972@@@@@@PSM',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'PSM',
            'tag': '[\'FinalDirector’sInterestNotice\']',
            'title': 'Final Directors Interest Notice',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:39:38Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159914.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159914@@@@@3A526546@@@@@@RD1',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'RD1',
            'tag': '[\'IssuedCapital–Other\']',
            'title': 'Release from escrow of restricted securities',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:39:08Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159913.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159913@@@@@6A949971@@@@@@RCE',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'RCE',
            'tag': '[\'CleansingNotice\']',
            'title': 'Cleansing Statement',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:31:18Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159912.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159912@@@@@6A949970@@@@@@NTI',
            'page_count': 62,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'NTI',
            'tag': '[\'NoticeofAnnualGeneralMeeting\',\'ProxyForm\']',
            'title': 'Notice of Annual General Meeting/Proxy Form',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:30:48Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159911.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159911@@@@@2A1180166@@@@@@URF',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'URF',
            'tag': '[\'NetTangibleAssetBacking\']',
            'title': 'Weekly NAV Estimate',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:24:53Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159910.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159910@@@@@6A949969@@@@@@TEG',
            'page_count': 58,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'TEG',
            'tag': '[\'NoticeofAnnualGeneralMeeting\',\'ProxyForm\']',
            'title': 'Notice of Annual General Meeting/Proxy Form',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:24:23Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159909.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159909@@@@@6A949968@@@@@@RCE',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'RCE',
            'tag': '[\'Alterationtoissuedcapital\']',
            'title': 'Notice under ASX Listing Rule 3.10.5A',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:23:03Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159908.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159908@@@@@2A1180164@@@@@@TTB',
            'page_count': 11,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'TTB',
            'tag': '[\'Becomingasubstantialholder\']',
            'title': 'Becoming a substantial holder from  MUFG',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:20:23Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159907.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159907@@@@@2A1180163@@@@@@AUB',
            'page_count': 117,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'AUB',
            'tag': '[\'Changeinsubstantialholding\']',
            'title': 'Change in substantial holding from MUFG',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:19:18Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159906.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159906@@@@@2A1180165@@@@@@OFX',
            'page_count': 3,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'OFX',
            'tag': '[\'Ceasingtobeasubstantialholder\']',
            'title': 'Ceasing to be a substantial holder',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:18:18Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159905.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159905@@@@@6A949966@@@@@@RCE',
            'page_count': 13,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'RCE',
            'tag': '[\'Appendix3B\']',
            'title': 'Appendix 3B',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:17:12Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159904.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159904@@@@@6A949965@@@@@@PSM',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'PSM',
            'tag': '[\'DirectorAppointment/Resignation\']',
            'title': 'Change to Board',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:16:12Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159903.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159903@@@@@3A526545@@@@@@BOL',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'BOL',
            'tag': '[\'DailyShareBuy-BackNotice\']',
            'title': 'Daily share buy-back notice - Appendix 3E',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:11:37Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159902.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159902@@@@@3A526544@@@@@@PTX',
            'page_count': 17,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'PTX',
            'tag': '[\'NoticeofAnnualGeneralMeeting\',\'ProxyForm\']',
            'title': 'Notice of Annual General Meeting/Proxy Form',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:11:12Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159901.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159901@@@@@6A949964@@@@@@PDN',
            'page_count': 19,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'PDN',
            'tag': '[\'CompanyPresentation(coverspresentationonbusinessupdates,projects,activitiesandothersthatacompanywillreportaspresentation)\']',
            'title': 'New York Investor Presentation',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:09:12Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159900.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159900@@@@@2A1180162@@@@@@AD8',
            'page_count': 9,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'AD8',
            'tag': '[\'Appendix3B\']',
            'title': 'Appendix 3B',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:08:17Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159899.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159899@@@@@6A949963@@@@@@BRB',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'BRB',
            'tag': '[\'Changeinsubstantialholding\']',
            'title': 'Change in substantial holding',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:07:42Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159898.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159898@@@@@6A949962@@@@@@BRB',
            'page_count': 7,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'BRB',
            'tag': '[\'ChangeofDirector’sInterestNotice\']',
            'title': 'Change of Directors Interest Notice x3',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T06:07:02Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159897.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159897@@@@@2A1180161@@@@@@YTM',
            'page_count': 2,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'YTM',
            'tag': '[\'NetTangibleAssetBacking\',\'IssuedCapital–Other\']',
            'title': 'NAV OF XTBs ON ISSUE',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:59:42Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159896.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159896@@@@@6A949961@@@@@@HLX',
            'page_count': 9,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'HLX',
            'tag': '[\'NoticeofAnnualGeneralMeeting\']',
            'title': 'Notice of Annual General Meeting',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:59:07Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159895.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159895@@@@@2A1180160@@@@@@CTW',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'CTW',
            'tag': '[\'StructuredProducts–Other\']',
            'title': 'CitiFirst MINI stop loss trigger event 16 Oct 19',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:57:47Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159894.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159894@@@@@2A1180159@@@@@@FGG',
            'page_count': 4,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'FGG',
            'tag': '[\'DividendReinvestmentPlan\',\'DividendRecordDate\',\'DividendPayDate\',\'DividendRate\']',
            'title': 'Update - Dividend/Distribution - FGG',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:54:47Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159893.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159893@@@@@6A949960@@@@@@AZM',
            'page_count': 49,
            'sign': '[\'PriceSensitive\']',
            'source': 'ASX',
            'status': 'active',
            'symbol': 'AZM',
            'tag': '[\'Target’sStatement–Off-marketbid\',\'Directors’StatementreTakeover\']',
            'title': 'Targets Statement',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:54:07Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159892.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159892@@@@@2A1180158@@@@@@FGX',
            'page_count': 4,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'FGX',
            'tag': '[\'DividendReinvestmentPlan\',\'DividendRecordDate\',\'DividendPayDate\',\'DividendRate\']',
            'title': 'Update - Dividend/Distribution - FGX',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:50:52Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159891.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159891@@@@@2A1180153@@@@@@XPL',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'XPL',
            'tag': '[\'CompanyAdministration–Other\']',
            'title': 'Notice from AusIndustry',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:50:17Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159890.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159890@@@@@2A1180157@@@@@@CTW',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'CTW',
            'tag': '[\'StructuredProductsDistribution\']',
            'title': 'CitiFirst WAM SFI MINIs Dividend Announcement',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:49:42Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159889.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159889@@@@@2A1180156@@@@@@PAF',
            'page_count': 9,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'PAF',
            'tag': '[\'PeriodicReports–Other\']',
            'title': 'Quarterly Report and video update - 30 September 2019',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:48:12Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159888.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159888@@@@@2A1180155@@@@@@PGF',
            'page_count': 9,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'PGF',
            'tag': '[\'ProgressReport–Other\']',
            'title': 'Quarterly Report and video update - 30 September 2019',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:47:47Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159887.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159887@@@@@3A526543@@@@@@TFL',
            'page_count': 14,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'TFL',
            'tag': '[\'Appendix3B\']',
            'title': 'Appendix 3B - 1.5M options',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:47:07Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159886.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159886@@@@@6A949959@@@@@@BCB',
            'page_count': 11,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'BCB',
            'tag': '[\'Appendix3B\']',
            'title': 'Appendix 3B',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:46:42Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159885.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159885@@@@@2A1180154@@@@@@PGF',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'PGF',
            'tag': '[\'ProgressReport–Other\']',
            'title': 'Quarterly video update - 30 September 2019',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:46:07Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159884.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159884@@@@@2A1180152@@@@@@MOT',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'MOT',
            'tag': '[\'NetTangibleAssetBacking\']',
            'title': 'Daily Fund Update',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:41:32Z',
            'user_readed': null
        },
        {
            'link': 'https://storage.googleapis.com/equix-asx-news-prod/news-asx/20191016/02159883.pdf',
            'link_paritech': null,
            'news_id': '20191016@@@@@@02159883@@@@@2A1180151@@@@@@MXT',
            'page_count': 1,
            'source': 'ASX',
            'status': 'active',
            'symbol': 'MXT',
            'tag': '[\'NetTangibleAssetBacking\']',
            'title': 'Daily Fund Update',
            'trading_halt': 0,
            'type_news': 'announcement',
            'updated': '2019-10-16T05:41:07Z',
            'user_readed': null
        }
    ]
}
