export default {
    overview: 'Overview',
    drawerIOS: 'Drawer IOS',
    drawerAndroid: 'Drawer Android',
    universalSearch: 'Universal Search',
    universalSearchDetail: 'Search Detail',
    newOrder: 'New Order',
    personal: 'Tab Personal',
    watchlistIndicies: 'Tab Indicies',
    top20: 'Tab S&P 20',
    top50: 'Tab S&P 50',
    top100: 'Tab S&P 100',
    top200: 'Tab S&P 200',
    nyse1: 'tradable-NYSE-01',
    nyse2: 'tradable-NYSE-02',
    nyse3: 'tradable-NYSE-03',
    nyse4: 'tradable-NYSE-04',
    nyse5: 'tradable-NYSE-05',
    nasdaq1: 'tradable-NASDAQ-01',
    nasdaq2: 'tradable-NASDAQ-02',
    xase: 'tradable-XASE',
    arcx: 'tradable-ARCX',
    watchListTopPrice: 'Tab Top Price',
    watchListTopValue: 'Tab Top Value',
    addcode: 'Add Code',
    addCodeSearch: 'Add Code Search',
    orders: 'Tab Open',
    ordersStopLoss: 'Tab Stop Loss',
    ordersFilled: 'Tab Filled',
    ordersCancelled: 'Tab Cancelled',
    portfolio: 'Portfolio',
    news: 'News',
    report: 'Report',
    reportFinancial: 'Financial Summary',
    reportHolding: 'Holding Valuation',
    reportCashSummary: 'Cash Account Summary',
    reportTransaction: 'Report Transaction',
    settings: 'Settings',
    settingsAuth: 'Authentication',
    settingsNews: 'News Notifications',
    settingsOrder: 'Order Notifications',
    userInfo: 'User Info',
    aboutUs: 'About Us',
    terms: 'Terms',
    modifyOrder: 'Modify Order',
    newsSearch: 'News Search',
    cnoteSearch: 'Contract Search',
    newsDetail: 'News Detail',
    contractDetail: 'Contract Detail',
    orderSearch: 'Order Search',
    schedule: 'News Schedule',
    updateMe: 'Update Me',
    connecting: 'Connecting',
    losers: 'Tab Losers',
    businessLog: 'Business Log',
    businessLogSearch: 'Contract Search'
}
