export default {
    'INVALID_PARAMS': '',
    'INVALID_MAPPING': 'INVALID_MAPPING',
    'ACCOUNT_LOCKED': 'ACCOUNT_LOCKED',
    'PENDING_VERIFICATION': 'PENDING_VERIFICATION',
    'PARITECH_PENDING_VERIFICATION': 'PARITECH_PENDING_VERIFICATION',
    'ENTER_NEW_EMAIL_AND_NEW_PASSWORD': 2059, // 3 input
    'ENTER_NEW_PASSWORD': 2057, // 2 input
    'EXPIRED_TOKEN_SET_PIN': 2089
};
