export default {
	ACCOUNT_AUTO: 'ACCOUNT AUTO',
	ASX: 'ASX',
	ASXCP: 'ASXCP',
	AUTO: 'AUTO',
	AUTODESK: 'AUTODESK',
	AUTO_TRADE: 'AUTO_TRADE',
	BESTMKT: 'BESTMKT',
	CXA: 'CXA',
	DESK: 'DESK',
	FIXED_CO: 'FIXED CO',
	IFDONE: 'IFDONE',
	OCO: 'OCO',
	TRAILCO: 'TRAILING CO'
};
