export default {
	'CP-MARKET': 'CP-Market',
	AMOUNT: 'Amount',
	ANY_PRICE_BLOCK: 'Any Price Block',
	AUCTION_IMBALANCE: 'Auction Imbalance',
	BEST: 'Best',
	DARK_LIMIT: 'Dark Limit',
	FUNARI: 'Funari',
	LIMIT: 'Limit',
	LIMIT_ON_CLOSE: 'Limit on Close',
	LIMIT_ON_OPEN: 'Limit on Open',
	LIMIT_OR_BETTER: 'Limit or Better',
	LIMIT_PLUS: 'Limit+',
	MARKET: 'Market',
	MARKET_AT_BEST: 'Market At Best',
	MARKET_ON_CLOSE: 'Market On Close',
	MARKET_ON_OPEN: 'Market on Open',
	MARKET_PLUS_TO_LIMIT: 'Market+ to Limit',
	MARKET_TO_LIMIT: 'Market to Limit',
	NOT_APPLICABLE: 'Not Applicable',
	OSM: 'OSM',
	OSP: 'OSP',
	PEGGED: 'Pegged',
	PERCENTAGE: 'Percentage',
	PRE_MARKET_US: 'Pre-market US',
	UNIT: 'Unit',
	VALUE: 'Value',
	VOLUME_MATCH: 'Volume Match',
	VWAP: 'VWAP'
};
