export default {
    // New enum
    add_code_search: 'Add Code - Load data when search symbol',
    load_data_annoucement: 'Annoucement - Load data',
    start_app_ios: 'Start App IOS',
    start_app_android: 'Start App Android',
    login_default_account: 'Login with default account',
    login_default_account_success: 'Login with default account - Success',
    login_default_account_fail: 'Login with default account - Failed',
    auto_login: 'Start function autoLogin',
    load_data_and_start_app_success: 'Load data & start app success',
    get_search_history: 'Universal Search - Get search history',
    load_data_overview: 'Overview - Load data',
    click_to_refresh: 'Click to refresh',
    overview_c2r: 'Overview - Click to refresh',
    new_order_c2r: 'New Order - Click to refresh',
    portfolio_c2r: 'Portfolio - Click to refresh',
    watch_list_c2r: 'Watch List - Click to refresh',
    load_data_order: 'New Order - Load price',
    show_form_order: 'Open New Order',
    show_form_personal: 'Open Personal',
    show_form_top_price: 'Open Tab Top Price',
    show_form_top_value: 'Open Tab Top Value',
    show_form_portfolio: 'Open Portfolio',
    show_form_add_code: 'Open Form Add Code',
    show_form_add_code_search: 'Open Form Add Code Search',
    change_watch_list_display: 'Change Watch List Display',
    load_data_top_value_item: 'Top Value - Load item data',
    load_data_top_value: 'Top Value - Load list item',
    show_form_orders: 'Open Orders',
    show_form_open_order: 'Open Tab Working Order',
    show_form_stop_loss_order: 'Open Tab Stop Loss Order',
    show_form_filled_order: 'Open Tab Filled Order',
    show_form_cancelled_order: 'Open Tab Canncelled Order',
    load_data_tab_filled: 'Tab Filled - Load data',
    load_data_tab_cancelled: 'Tab Cancelled - Load data',
    load_data_tab_open: 'Tab Working - Load data',
    load_data_tab_stop_loss: 'Tab Stop Loss -  Load data',
    load_data_form_orders: 'Orders - Load data',
    load_data_form_portfolio: 'Portfolio - Load data',
    cancel_order: 'Request Cancel Order',
    load_data_news: 'News - Load data',
    load_data_cnote: 'Contract note - Load data',
    load_data_form_universal_search: 'Universal Search - Load data',
    get_symbol_info: 'Symbol - Load info',
    get_data_price_indicies: 'Indicies - Get Data Price',
    get_data_price_search_detail: 'Search Detail - Get Data Price',
    show_form_about_us: 'Open About Us',
    click_to_website: 'Click to website',
    click_sign_out: 'Click Sign Out',
    show_annoucement: 'Open Annoucement',
    show_form_disclaimer: 'Open Term of Use',
    show_report_financial: 'Open Report Financial',
    show_market_caps: 'Open Market Caps',
    show_report_holding: 'Open Report Holding',
    load_data_report_holding: 'Report Holding - Load data',
    load_company_name: 'Holding - Load company name',
    show_form_watch_list: 'Open Watch List',
    get_user_price_source: 'Get User Price Source',
    sign_out_action: 'Sign Out Request',
    set_data_login: 'Set Data Login',
    show_10_trades: 'Swiper - Show Ten Trades',
    get_filled_data: 'Ten Trades - Get filled data',
    show_swiper_chart: 'Swiper - Show Chart',
    load_data_chart: 'Swiper Chart - Load data',
    load_data_chart_indicies: 'Market Depth Indicies - Load data',
    load_data_from_api_chart: 'Market Depth Chart - Load data from api',
    load_data_from_api_modify_order: 'Modify Order - Load data from api',
    load_data_from_api_watch_list: 'Watch List Chart Item - Load data from api',
    show_swiper_market_depth: 'Swiper - Show Market Depth',
    get_data_ref: 'Swiper - Get Market Depth Data',
    show_swiper_news: 'Swiper - Show News',
    get_data_news: 'News - Load data',
    show_swiper_orders: 'Swiper - Show Orders',
    show_swiper_position: 'Swiper - Show Position',
    show_form_modify_order: 'Open Modify Order',
    get_fees: 'Get Fees',
    show_form_overview: 'Open Overview',
    get_cash_available_overview: 'Overview - Get Cash available',
    get_cash_available_modify_order: 'Modify Order - Get Cash available',
    get_data_overview: 'Overview - Load data',
    get_data_chart_indicies: 'Indicies Item - Get data chart',
    show_form_news_delayed: 'Open News Delayed',
    show_form_news_parent: 'Open News',
    show_form_contract_note: 'Open Contract Note',
    get_position: 'News - Get position',
    show_form_news_search: 'Open News Search',
    show_form_cnote_search: 'Open Contract Note Search',
    show_form_news_detail: 'Open News Search Details',
    show_form_cnote_detail: 'Open Contract Note Search Details',
    get_order_transaction_portfolio: 'Portfolio - Get order transaction',
    get_order_transaction_orders: 'Orders - Get order transaction',
    get_data_history: 'Portfolio - Get top order transaction',
    show_form_order_search: 'Open Order Search',
    send_order_request: 'Send Order Request',
    load_order_history: 'Load Order History',
    show_order_history: 'Show Order History',
    show_form_report: 'Open Report',
    show_news_schedule: 'News - Set Time Do not Disturb',
    show_form_news_settings: 'Open News Settings',
    show_form_order_settings: 'Open Order Settings',
    show_form_settings: 'Open Settings',
    get_top_company: 'Get Top Company',
    show_universal_search_detail: 'Universal Search - Details',
    get_data_market_depth: 'Market Depth - Load data',
    get_data_cos: 'COS - Load data',
    show_form_update_me: 'Open Update Me',
    get_user_info: 'Get User Info',
    show_form_user_info: 'Open User Info',
    show_form_updating: 'Show Form Updating',
    cash_account_summary: 'Show Report Cash Account Summary',
    load_data_report_cash_summary: 'Report - Cash Account Summary Load Data',
    show_form_connecting: 'Show Form Connecting',
    show_form_business_log: 'Show Form Business Log',
    show_form_business_log_search: 'Open Business Log Search'
}
