export default TIME_ZONE = [
    { key: '0', location: 'Etc/GMT-14', timezone: 14, value: '(GMT+14:00) Etc, GMT-14' },
    { key: '1', location: 'Pacific/Kiritimati', timezone: 14, value: '(GMT+14:00) Pacific, Kiritimati' },
    { key: '2', location: 'Etc/GMT-13', timezone: 13, value: '(GMT+13:00) Etc, GMT-13' },
    { key: '3', location: 'Pacific/Apia', timezone: 13, value: '(GMT+13:00) Pacific, Apia' },
    { key: '4', location: 'Pacific/Enderbury', timezone: 13, value: '(GMT+13:00) Pacific, Enderbury' },
    { key: '5', location: 'Pacific/Fakaofo', timezone: 13, value: '(GMT+13:00) Pacific, Fakaofo' },
    { key: '6', location: 'Pacific/Tongatapu', timezone: 13, value: '(GMT+13:00) Pacific, Tongatapu' },
    { key: '7', location: 'NZ-CHAT', timezone: 12.75, value: '(GMT+12:45) NZ-CHAT' },
    { key: '8', location: 'Pacific/Chatham', timezone: 12.75, value: '(GMT+12:45) Pacific, Chatham' },
    { key: '9', location: 'Antarctica/McMurdo', timezone: 12, value: '(GMT+12:00) Antarctica, McMurdo' },
    { key: '10', location: 'Antarctica/South_Pole', timezone: 12, value: '(GMT+12:00) Antarctica, South Pole' },
    { key: '11', location: 'Asia/Anadyr', timezone: 12, value: '(GMT+12:00) Asia, Anadyr' },
    { key: '12', location: 'Asia/Kamchatka', timezone: 12, value: '(GMT+12:00) Asia, Kamchatka' },
    { key: '13', location: 'Etc/GMT-12', timezone: 12, value: '(GMT+12:00) Etc, GMT-12' },
    { key: '14', location: 'Kwajalein', timezone: 12, value: '(GMT+12:00) Kwajalein' },
    { key: '15', location: 'NZ', timezone: 12, value: '(GMT+12:00) NZ' },
    { key: '16', location: 'Pacific/Auckland', timezone: 12, value: '(GMT+12:00) Pacific, Auckland' },
    { key: '17', location: 'Pacific/Fiji', timezone: 12, value: '(GMT+12:00) Pacific, Fiji' },
    { key: '18', location: 'Pacific/Funafuti', timezone: 12, value: '(GMT+12:00) Pacific, Funafuti' },
    { key: '19', location: 'Pacific/Kwajalein', timezone: 12, value: '(GMT+12:00) Pacific, Kwajalein' },
    { key: '20', location: 'Pacific/Majuro', timezone: 12, value: '(GMT+12:00) Pacific, Majuro' },
    { key: '21', location: 'Pacific/Nauru', timezone: 12, value: '(GMT+12:00) Pacific, Nauru' },
    { key: '22', location: 'Pacific/Tarawa', timezone: 12, value: '(GMT+12:00) Pacific, Tarawa' },
    { key: '23', location: 'Pacific/Wake', timezone: 12, value: '(GMT+12:00) Pacific, Wake' },
    { key: '24', location: 'Pacific/Wallis', timezone: 12, value: '(GMT+12:00) Pacific, Wallis' },
    { key: '25', location: 'Antarctica/Macquarie', timezone: 11, value: '(GMT+11:00) Antarctica, Macquarie' },
    { key: '26', location: 'Asia/Magadan', timezone: 11, value: '(GMT+11:00) Asia, Magadan' },
    { key: '27', location: 'Asia/Sakhalin', timezone: 11, value: '(GMT+11:00) Asia, Sakhalin' },
    { key: '28', location: 'Asia/Srednekolymsk', timezone: 11, value: '(GMT+11:00) Asia, Srednekolymsk' },
    { key: '29', location: 'Etc/GMT-11', timezone: 11, value: '(GMT+11:00) Etc, GMT-11' },
    { key: '30', location: 'Pacific/Bougainville', timezone: 11, value: '(GMT+11:00) Pacific, Bougainville' },
    { key: '31', location: 'Pacific/Efate', timezone: 11, value: '(GMT+11:00) Pacific, Efate' },
    { key: '32', location: 'Pacific/Guadalcanal', timezone: 11, value: '(GMT+11:00) Pacific, Guadalcanal' },
    { key: '33', location: 'Pacific/Kosrae', timezone: 11, value: '(GMT+11:00) Pacific, Kosrae' },
    { key: '34', location: 'Pacific/Norfolk', timezone: 11, value: '(GMT+11:00) Pacific, Norfolk' },
    { key: '35', location: 'Pacific/Noumea', timezone: 11, value: '(GMT+11:00) Pacific, Noumea' },
    { key: '36', location: 'Pacific/Pohnpei', timezone: 11, value: '(GMT+11:00) Pacific, Pohnpei' },
    { key: '37', location: 'Pacific/Ponape', timezone: 11, value: '(GMT+11:00) Pacific, Ponape' },
    { key: '38', location: 'Australia/LHI', timezone: 10.5, value: '(GMT+10:30) Australia, LHI' },
    { key: '39', location: 'Australia/Lord_Howe', timezone: 10.5, value: '(GMT+10:30) Australia, Lord Howe' },
    { key: '40', location: 'Antarctica/DumontDUrville', timezone: 10, value: '(GMT+10:00) Antarctica, DumontDUrville' },
    { key: '41', location: 'Asia/Ust-Nera', timezone: 10, value: '(GMT+10:00) Asia, Ust-Nera' },
    { key: '42', location: 'Asia/Vladivostok', timezone: 10, value: '(GMT+10:00) Asia, Vladivostok' },
    { key: '43', location: 'Australia/ACT', timezone: 10, value: '(GMT+10:00) Australia, ACT' },
    { key: '44', location: 'Australia/Brisbane', timezone: 10, value: '(GMT+10:00) Australia, Brisbane' },
    { key: '45', location: 'Australia/Canberra', timezone: 10, value: '(GMT+10:00) Australia, Canberra' },
    { key: '46', location: 'Australia/Currie', timezone: 10, value: '(GMT+10:00) Australia, Currie' },
    { key: '47', location: 'Australia/Hobart', timezone: 10, value: '(GMT+10:00) Australia, Hobart' },
    { key: '48', location: 'Australia/Lindeman', timezone: 10, value: '(GMT+10:00) Australia, Lindeman' },
    { key: '49', location: 'Australia/Melbourne', timezone: 10, value: '(GMT+10:00) Australia, Melbourne' },
    { key: '50', location: 'Australia/NSW', timezone: 10, value: '(GMT+10:00) Australia, NSW' },
    { key: '51', location: 'Australia/Queensland', timezone: 10, value: '(GMT+10:00) Australia, Queensland' },
    { key: '52', location: 'Australia/Sydney', timezone: 10, value: '(GMT+10:00) Australia, Sydney' },
    { key: '53', location: 'Australia/Tasmania', timezone: 10, value: '(GMT+10:00) Australia, Tasmania' },
    { key: '54', location: 'Australia/Victoria', timezone: 10, value: '(GMT+10:00) Australia, Victoria' },
    { key: '55', location: 'Etc/GMT-10', timezone: 10, value: '(GMT+10:00) Etc, GMT-10' },
    { key: '56', location: 'Pacific/Chuuk', timezone: 10, value: '(GMT+10:00) Pacific, Chuuk' },
    { key: '57', location: 'Pacific/Guam', timezone: 10, value: '(GMT+10:00) Pacific, Guam' },
    { key: '58', location: 'Pacific/Port_Moresby', timezone: 10, value: '(GMT+10:00) Pacific, Port Moresby' },
    { key: '59', location: 'Pacific/Saipan', timezone: 10, value: '(GMT+10:00) Pacific, Saipan' },
    { key: '60', location: 'Pacific/Truk', timezone: 10, value: '(GMT+10:00) Pacific, Truk' },
    { key: '61', location: 'Pacific/Yap', timezone: 10, value: '(GMT+10:00) Pacific, Yap' },
    { key: '62', location: 'Australia/Adelaide', timezone: 9.5, value: '(GMT+09:30) Australia, Adelaide' },
    { key: '63', location: 'Australia/Broken_Hill', timezone: 9.5, value: '(GMT+09:30) Australia, Broken Hill' },
    { key: '64', location: 'Australia/Darwin', timezone: 9.5, value: '(GMT+09:30) Australia, Darwin' },
    { key: '65', location: 'Australia/North', timezone: 9.5, value: '(GMT+09:30) Australia, North' },
    { key: '66', location: 'Australia/South', timezone: 9.5, value: '(GMT+09:30) Australia, South' },
    { key: '67', location: 'Australia/Yancowinna', timezone: 9.5, value: '(GMT+09:30) Australia, Yancowinna' },
    { key: '68', location: 'Asia/Chita', timezone: 9, value: '(GMT+09:00) Asia, Chita' },
    { key: '69', location: 'Asia/Dili', timezone: 9, value: '(GMT+09:00) Asia, Dili' },
    { key: '70', location: 'Asia/Jayapura', timezone: 9, value: '(GMT+09:00) Asia, Jayapura' },
    { key: '71', location: 'Asia/Khandyga', timezone: 9, value: '(GMT+09:00) Asia, Khandyga' },
    { key: '72', location: 'Asia/Pyongyang', timezone: 9, value: '(GMT+09:00) Asia, Pyongyang' },
    { key: '73', location: 'Asia/Seoul', timezone: 9, value: '(GMT+09:00) Asia, Seoul' },
    { key: '74', location: 'Asia/Tokyo', timezone: 9, value: '(GMT+09:00) Asia, Tokyo' },
    { key: '75', location: 'Asia/Yakutsk', timezone: 9, value: '(GMT+09:00) Asia, Yakutsk' },
    { key: '76', location: 'Etc/GMT-9', timezone: 9, value: '(GMT+09:00) Etc, GMT-9' },
    { key: '77', location: 'Japan', timezone: 9, value: '(GMT+09:00) Japan' },
    { key: '78', location: 'Pacific/Palau', timezone: 9, value: '(GMT+09:00) Pacific, Palau' },
    { key: '79', location: 'ROK', timezone: 9, value: '(GMT+09:00) ROK' },
    { key: '80', location: 'Australia/Eucla', timezone: 8.75, value: '(GMT+08:45) Australia, Eucla' },
    { key: '81', location: 'Antarctica/Casey', timezone: 8, value: '(GMT+08:00) Antarctica, Casey' },
    { key: '82', location: 'Asia/Brunei', timezone: 8, value: '(GMT+08:00) Asia, Brunei' },
    { key: '83', location: 'Asia/Choibalsan', timezone: 8, value: '(GMT+08:00) Asia, Choibalsan' },
    { key: '84', location: 'Asia/Chongqing', timezone: 8, value: '(GMT+08:00) Asia, Chongqing' },
    { key: '85', location: 'Asia/Chungking', timezone: 8, value: '(GMT+08:00) Asia, Chungking' },
    { key: '86', location: 'Asia/Harbin', timezone: 8, value: '(GMT+08:00) Asia, Harbin' },
    { key: '87', location: 'Asia/Hong_Kong', timezone: 8, value: '(GMT+08:00) Asia, Hong Kong' },
    { key: '88', location: 'Asia/Irkutsk', timezone: 8, value: '(GMT+08:00) Asia, Irkutsk' },
    { key: '89', location: 'Asia/Kuala_Lumpur', timezone: 8, value: '(GMT+08:00) Asia, Kuala Lumpur' },
    { key: '90', location: 'Asia/Kuching', timezone: 8, value: '(GMT+08:00) Asia, Kuching' },
    { key: '91', location: 'Asia/Macao', timezone: 8, value: '(GMT+08:00) Asia, Macao' },
    { key: '92', location: 'Asia/Macau', timezone: 8, value: '(GMT+08:00) Asia, Macau' },
    { key: '93', location: 'Asia/Makassar', timezone: 8, value: '(GMT+08:00) Asia, Makassar' },
    { key: '94', location: 'Asia/Manila', timezone: 8, value: '(GMT+08:00) Asia, Manila' },
    { key: '95', location: 'Asia/Shanghai', timezone: 8, value: '(GMT+08:00) Asia, Shanghai' },
    { key: '96', location: 'Asia/Singapore', timezone: 8, value: '(GMT+08:00) Asia, Singapore' },
    { key: '97', location: 'Asia/Taipei', timezone: 8, value: '(GMT+08:00) Asia, Taipei' },
    { key: '98', location: 'Asia/Ujung_Pandang', timezone: 8, value: '(GMT+08:00) Asia, Ujung Pandang' },
    { key: '99', location: 'Asia/Ulaanbaatar', timezone: 8, value: '(GMT+08:00) Asia, Ulaanbaatar' },
    { key: '100', location: 'Asia/Ulan_Bator', timezone: 8, value: '(GMT+08:00) Asia, Ulan Bator' },
    { key: '101', location: 'Australia/Perth', timezone: 8, value: '(GMT+08:00) Australia, Perth' },
    { key: '102', location: 'Australia/West', timezone: 8, value: '(GMT+08:00) Australia, West' },
    { key: '103', location: 'Etc/GMT-8', timezone: 8, value: '(GMT+08:00) Etc, GMT-8' },
    { key: '104', location: 'Hongkong', timezone: 8, value: '(GMT+08:00) Hongkong' },
    { key: '105', location: 'PRC', timezone: 8, value: '(GMT+08:00) PRC' },
    { key: '106', location: 'ROC', timezone: 8, value: '(GMT+08:00) ROC' },
    { key: '107', location: 'Singapore', timezone: 8, value: '(GMT+08:00) Singapore' },
    { key: '108', location: 'Antarctica/Davis', timezone: 7, value: '(GMT+07:00) Antarctica, Davis' },
    { key: '109', location: 'Asia/Bangkok', timezone: 7, value: '(GMT+07:00) Asia, Bangkok' },
    { key: '110', location: 'Asia/Barnaul', timezone: 7, value: '(GMT+07:00) Asia, Barnaul' },
    { key: '111', location: 'Asia/Ho_Chi_Minh', timezone: 7, value: '(GMT+07:00) Asia, Ho Chi Minh' },
    { key: '112', location: 'Asia/Hovd', timezone: 7, value: '(GMT+07:00) Asia, Hovd' },
    { key: '113', location: 'Asia/Jakarta', timezone: 7, value: '(GMT+07:00) Asia, Jakarta' },
    { key: '114', location: 'Asia/Krasnoyarsk', timezone: 7, value: '(GMT+07:00) Asia, Krasnoyarsk' },
    { key: '115', location: 'Asia/Novokuznetsk', timezone: 7, value: '(GMT+07:00) Asia, Novokuznetsk' },
    { key: '116', location: 'Asia/Novosibirsk', timezone: 7, value: '(GMT+07:00) Asia, Novosibirsk' },
    { key: '117', location: 'Asia/Phnom_Penh', timezone: 7, value: '(GMT+07:00) Asia, Phnom Penh' },
    { key: '118', location: 'Asia/Pontianak', timezone: 7, value: '(GMT+07:00) Asia, Pontianak' },
    { key: '119', location: 'Asia/Saigon', timezone: 7, value: '(GMT+07:00) Asia, Saigon' },
    { key: '120', location: 'Asia/Tomsk', timezone: 7, value: '(GMT+07:00) Asia, Tomsk' },
    { key: '121', location: 'Asia/Vientiane', timezone: 7, value: '(GMT+07:00) Asia, Vientiane' },
    { key: '122', location: 'Etc/GMT-7', timezone: 7, value: '(GMT+07:00) Etc, GMT-7' },
    { key: '123', location: 'Indian/Christmas', timezone: 7, value: '(GMT+07:00) Indian, Christmas' },
    { key: '124', location: 'Asia/Rangoon', timezone: 6.5, value: '(GMT+06:30) Asia, Rangoon' },
    { key: '125', location: 'Asia/Yangon', timezone: 6.5, value: '(GMT+06:30) Asia, Yangon' },
    { key: '126', location: 'Indian/Cocos', timezone: 6.5, value: '(GMT+06:30) Indian, Cocos' },
    { key: '127', location: 'Antarctica/Vostok', timezone: 6, value: '(GMT+06:00) Antarctica, Vostok' },
    { key: '128', location: 'Asia/Almaty', timezone: 6, value: '(GMT+06:00) Asia, Almaty' },
    { key: '129', location: 'Asia/Bishkek', timezone: 6, value: '(GMT+06:00) Asia, Bishkek' },
    { key: '130', location: 'Asia/Dacca', timezone: 6, value: '(GMT+06:00) Asia, Dacca' },
    { key: '131', location: 'Asia/Dhaka', timezone: 6, value: '(GMT+06:00) Asia, Dhaka' },
    { key: '132', location: 'Asia/Kashgar', timezone: 6, value: '(GMT+06:00) Asia, Kashgar' },
    { key: '133', location: 'Asia/Omsk', timezone: 6, value: '(GMT+06:00) Asia, Omsk' },
    { key: '134', location: 'Asia/Qyzylorda', timezone: 6, value: '(GMT+06:00) Asia, Qyzylorda' },
    { key: '135', location: 'Asia/Thimbu', timezone: 6, value: '(GMT+06:00) Asia, Thimbu' },
    { key: '136', location: 'Asia/Thimphu', timezone: 6, value: '(GMT+06:00) Asia, Thimphu' },
    { key: '137', location: 'Asia/Urumqi', timezone: 6, value: '(GMT+06:00) Asia, Urumqi' },
    { key: '138', location: 'Etc/GMT-6', timezone: 6, value: '(GMT+06:00) Etc, GMT-6' },
    { key: '139', location: 'Indian/Chagos', timezone: 6, value: '(GMT+06:00) Indian, Chagos' },
    { key: '140', location: 'Asia/Kathmandu', timezone: 5.75, value: '(GMT+05:45) Asia, Kathmandu' },
    { key: '141', location: 'Asia/Katmandu', timezone: 5.75, value: '(GMT+05:45) Asia, Katmandu' },
    { key: '142', location: 'Asia/Calcutta', timezone: 5.5, value: '(GMT+05:30) Asia, Calcutta' },
    { key: '143', location: 'Asia/Colombo', timezone: 5.5, value: '(GMT+05:30) Asia, Colombo' },
    { key: '144', location: 'Asia/Kolkata', timezone: 5.5, value: '(GMT+05:30) Asia, Kolkata' },
    { key: '145', location: 'Antarctica/Mawson', timezone: 5, value: '(GMT+05:00) Antarctica, Mawson' },
    { key: '146', location: 'Asia/Aqtau', timezone: 5, value: '(GMT+05:00) Asia, Aqtau' },
    { key: '147', location: 'Asia/Aqtobe', timezone: 5, value: '(GMT+05:00) Asia, Aqtobe' },
    { key: '148', location: 'Asia/Ashgabat', timezone: 5, value: '(GMT+05:00) Asia, Ashgabat' },
    { key: '149', location: 'Asia/Ashkhabad', timezone: 5, value: '(GMT+05:00) Asia, Ashkhabad' },
    { key: '150', location: 'Asia/Atyrau', timezone: 5, value: '(GMT+05:00) Asia, Atyrau' },
    { key: '151', location: 'Asia/Dushanbe', timezone: 5, value: '(GMT+05:00) Asia, Dushanbe' },
    { key: '152', location: 'Asia/Karachi', timezone: 5, value: '(GMT+05:00) Asia, Karachi' },
    { key: '153', location: 'Asia/Oral', timezone: 5, value: '(GMT+05:00) Asia, Oral' },
    { key: '154', location: 'Asia/Samarkand', timezone: 5, value: '(GMT+05:00) Asia, Samarkand' },
    { key: '155', location: 'Asia/Tashkent', timezone: 5, value: '(GMT+05:00) Asia, Tashkent' },
    { key: '156', location: 'Asia/Yekaterinburg', timezone: 5, value: '(GMT+05:00) Asia, Yekaterinburg' },
    { key: '157', location: 'Etc/GMT-5', timezone: 5, value: '(GMT+05:00) Etc, GMT-5' },
    { key: '158', location: 'Indian/Kerguelen', timezone: 5, value: '(GMT+05:00) Indian, Kerguelen' },
    { key: '159', location: 'Indian/Maldives', timezone: 5, value: '(GMT+05:00) Indian, Maldives' },
    { key: '160', location: 'Asia/Kabul', timezone: 4.5, value: '(GMT+04:30) Asia, Kabul' },
    { key: '161', location: 'Asia/Tehran', timezone: 4.5, value: '(GMT+04:30) Asia, Tehran' },
    { key: '162', location: 'Iran', timezone: 4.5, value: '(GMT+04:30) Iran' },
    { key: '163', location: 'Asia/Baku', timezone: 4, value: '(GMT+04:00) Asia, Baku' },
    { key: '164', location: 'Asia/Dubai', timezone: 4, value: '(GMT+04:00) Asia, Dubai' },
    { key: '165', location: 'Asia/Muscat', timezone: 4, value: '(GMT+04:00) Asia, Muscat' },
    { key: '166', location: 'Asia/Tbilisi', timezone: 4, value: '(GMT+04:00) Asia, Tbilisi' },
    { key: '167', location: 'Asia/Yerevan', timezone: 4, value: '(GMT+04:00) Asia, Yerevan' },
    { key: '168', location: 'Etc/GMT-4', timezone: 4, value: '(GMT+04:00) Etc, GMT-4' },
    { key: '169', location: 'Europe/Astrakhan', timezone: 4, value: '(GMT+04:00) Europe, Astrakhan' },
    { key: '170', location: 'Europe/Samara', timezone: 4, value: '(GMT+04:00) Europe, Samara' },
    { key: '171', location: 'Europe/Saratov', timezone: 4, value: '(GMT+04:00) Europe, Saratov' },
    { key: '172', location: 'Europe/Ulyanovsk', timezone: 4, value: '(GMT+04:00) Europe, Ulyanovsk' },
    { key: '173', location: 'Europe/Volgograd', timezone: 4, value: '(GMT+04:00) Europe, Volgograd' },
    { key: '174', location: 'Indian/Mahe', timezone: 4, value: '(GMT+04:00) Indian, Mahe' },
    { key: '175', location: 'Indian/Mauritius', timezone: 4, value: '(GMT+04:00) Indian, Mauritius' },
    { key: '176', location: 'Indian/Reunion', timezone: 4, value: '(GMT+04:00) Indian, Reunion' },
    { key: '177', location: 'Africa/Addis_Ababa', timezone: 3, value: '(GMT+03:00) Africa, Addis Ababa' },
    { key: '178', location: 'Africa/Asmara', timezone: 3, value: '(GMT+03:00) Africa, Asmara' },
    { key: '179', location: 'Africa/Asmera', timezone: 3, value: '(GMT+03:00) Africa, Asmera' },
    { key: '180', location: 'Africa/Dar_es_Salaam', timezone: 3, value: '(GMT+03:00) Africa, Dar es Salaam' },
    { key: '181', location: 'Africa/Djibouti', timezone: 3, value: '(GMT+03:00) Africa, Djibouti' },
    { key: '182', location: 'Africa/Juba', timezone: 3, value: '(GMT+03:00) Africa, Juba' },
    { key: '183', location: 'Africa/Kampala', timezone: 3, value: '(GMT+03:00) Africa, Kampala' },
    { key: '184', location: 'Africa/Mogadishu', timezone: 3, value: '(GMT+03:00) Africa, Mogadishu' },
    { key: '185', location: 'Africa/Nairobi', timezone: 3, value: '(GMT+03:00) Africa, Nairobi' },
    { key: '186', location: 'Antarctica/Syowa', timezone: 3, value: '(GMT+03:00) Antarctica, Syowa' },
    { key: '187', location: 'Asia/Aden', timezone: 3, value: '(GMT+03:00) Asia, Aden' },
    { key: '188', location: 'Asia/Amman', timezone: 3, value: '(GMT+03:00) Asia, Amman' },
    { key: '189', location: 'Asia/Baghdad', timezone: 3, value: '(GMT+03:00) Asia, Baghdad' },
    { key: '190', location: 'Asia/Bahrain', timezone: 3, value: '(GMT+03:00) Asia, Bahrain' },
    { key: '191', location: 'Asia/Beirut', timezone: 3, value: '(GMT+03:00) Asia, Beirut' },
    { key: '192', location: 'Asia/Damascus', timezone: 3, value: '(GMT+03:00) Asia, Damascus' },
    { key: '193', location: 'Asia/Famagusta', timezone: 3, value: '(GMT+03:00) Asia, Famagusta' },
    { key: '194', location: 'Asia/Gaza', timezone: 3, value: '(GMT+03:00) Asia, Gaza' },
    { key: '195', location: 'Asia/Hebron', timezone: 3, value: '(GMT+03:00) Asia, Hebron' },
    { key: '196', location: 'Asia/Istanbul', timezone: 3, value: '(GMT+03:00) Asia, Istanbul' },
    { key: '197', location: 'Asia/Jerusalem', timezone: 3, value: '(GMT+03:00) Asia, Jerusalem' },
    { key: '198', location: 'Asia/Kuwait', timezone: 3, value: '(GMT+03:00) Asia, Kuwait' },
    { key: '199', location: 'Asia/Nicosia', timezone: 3, value: '(GMT+03:00) Asia, Nicosia' },
    { key: '200', location: 'Asia/Qatar', timezone: 3, value: '(GMT+03:00) Asia, Qatar' },
    { key: '201', location: 'Asia/Riyadh', timezone: 3, value: '(GMT+03:00) Asia, Riyadh' },
    { key: '202', location: 'Asia/Tel_Aviv', timezone: 3, value: '(GMT+03:00) Asia, Tel Aviv' },
    { key: '203', location: 'EET', timezone: 3, value: '(GMT+03:00) EET' },
    { key: '204', location: 'Etc/GMT-3', timezone: 3, value: '(GMT+03:00) Etc, GMT-3' },
    { key: '205', location: 'Europe/Athens', timezone: 3, value: '(GMT+03:00) Europe, Athens' },
    { key: '206', location: 'Europe/Bucharest', timezone: 3, value: '(GMT+03:00) Europe, Bucharest' },
    { key: '207', location: 'Europe/Chisinau', timezone: 3, value: '(GMT+03:00) Europe, Chisinau' },
    { key: '208', location: 'Europe/Helsinki', timezone: 3, value: '(GMT+03:00) Europe, Helsinki' },
    { key: '209', location: 'Europe/Istanbul', timezone: 3, value: '(GMT+03:00) Europe, Istanbul' },
    { key: '210', location: 'Europe/Kiev', timezone: 3, value: '(GMT+03:00) Europe, Kiev' },
    { key: '211', location: 'Europe/Kirov', timezone: 3, value: '(GMT+03:00) Europe, Kirov' },
    { key: '212', location: 'Europe/Mariehamn', timezone: 3, value: '(GMT+03:00) Europe, Mariehamn' },
    { key: '213', location: 'Europe/Minsk', timezone: 3, value: '(GMT+03:00) Europe, Minsk' },
    { key: '214', location: 'Europe/Moscow', timezone: 3, value: '(GMT+03:00) Europe, Moscow' },
    { key: '215', location: 'Europe/Nicosia', timezone: 3, value: '(GMT+03:00) Europe, Nicosia' },
    { key: '216', location: 'Europe/Riga', timezone: 3, value: '(GMT+03:00) Europe, Riga' },
    { key: '217', location: 'Europe/Simferopol', timezone: 3, value: '(GMT+03:00) Europe, Simferopol' },
    { key: '218', location: 'Europe/Sofia', timezone: 3, value: '(GMT+03:00) Europe, Sofia' },
    { key: '219', location: 'Europe/Tallinn', timezone: 3, value: '(GMT+03:00) Europe, Tallinn' },
    { key: '220', location: 'Europe/Tiraspol', timezone: 3, value: '(GMT+03:00) Europe, Tiraspol' },
    { key: '221', location: 'Europe/Uzhgorod', timezone: 3, value: '(GMT+03:00) Europe, Uzhgorod' },
    { key: '222', location: 'Europe/Vilnius', timezone: 3, value: '(GMT+03:00) Europe, Vilnius' },
    { key: '223', location: 'Europe/Zaporozhye', timezone: 3, value: '(GMT+03:00) Europe, Zaporozhye' },
    { key: '224', location: 'Indian/Antananarivo', timezone: 3, value: '(GMT+03:00) Indian, Antananarivo' },
    { key: '225', location: 'Indian/Comoro', timezone: 3, value: '(GMT+03:00) Indian, Comoro' },
    { key: '226', location: 'Indian/Mayotte', timezone: 3, value: '(GMT+03:00) Indian, Mayotte' },
    { key: '227', location: 'Israel', timezone: 3, value: '(GMT+03:00) Israel' },
    { key: '228', location: 'Turkey', timezone: 3, value: '(GMT+03:00) Turkey' },
    { key: '229', location: 'W-SU', timezone: 3, value: '(GMT+03:00) W-SU' },
    { key: '230', location: 'Africa/Blantyre', timezone: 2, value: '(GMT+02:00) Africa, Blantyre' },
    { key: '231', location: 'Africa/Bujumbura', timezone: 2, value: '(GMT+02:00) Africa, Bujumbura' },
    { key: '232', location: 'Africa/Cairo', timezone: 2, value: '(GMT+02:00) Africa, Cairo' },
    { key: '233', location: 'Africa/Ceuta', timezone: 2, value: '(GMT+02:00) Africa, Ceuta' },
    { key: '234', location: 'Africa/Gaborone', timezone: 2, value: '(GMT+02:00) Africa, Gaborone' },
    { key: '235', location: 'Africa/Harare', timezone: 2, value: '(GMT+02:00) Africa, Harare' },
    { key: '236', location: 'Africa/Johannesburg', timezone: 2, value: '(GMT+02:00) Africa, Johannesburg' },
    { key: '237', location: 'Africa/Khartoum', timezone: 2, value: '(GMT+02:00) Africa, Khartoum' },
    { key: '238', location: 'Africa/Kigali', timezone: 2, value: '(GMT+02:00) Africa, Kigali' },
    { key: '239', location: 'Africa/Lubumbashi', timezone: 2, value: '(GMT+02:00) Africa, Lubumbashi' },
    { key: '240', location: 'Africa/Lusaka', timezone: 2, value: '(GMT+02:00) Africa, Lusaka' },
    { key: '241', location: 'Africa/Maputo', timezone: 2, value: '(GMT+02:00) Africa, Maputo' },
    { key: '242', location: 'Africa/Maseru', timezone: 2, value: '(GMT+02:00) Africa, Maseru' },
    { key: '243', location: 'Africa/Mbabane', timezone: 2, value: '(GMT+02:00) Africa, Mbabane' },
    { key: '244', location: 'Africa/Tripoli', timezone: 2, value: '(GMT+02:00) Africa, Tripoli' },
    { key: '245', location: 'Africa/Windhoek', timezone: 2, value: '(GMT+02:00) Africa, Windhoek' },
    { key: '246', location: 'Antarctica/Troll', timezone: 2, value: '(GMT+02:00) Antarctica, Troll' },
    { key: '247', location: 'Arctic/Longyearbyen', timezone: 2, value: '(GMT+02:00) Arctic, Longyearbyen' },
    { key: '248', location: 'Atlantic/Jan_Mayen', timezone: 2, value: '(GMT+02:00) Atlantic, Jan Mayen' },
    { key: '249', location: 'CET', timezone: 2, value: '(GMT+02:00) CET' },
    { key: '250', location: 'Egypt', timezone: 2, value: '(GMT+02:00) Egypt' },
    { key: '251', location: 'Etc/GMT-2', timezone: 2, value: '(GMT+02:00) Etc, GMT-2' },
    { key: '253', location: 'Europe/Andorra', timezone: 2, value: '(GMT+02:00) Europe, Andorra' },
    { key: '252', location: 'Europe/Amsterdam', timezone: 2, value: '(GMT+02:00) Europe, Amsterdam' },
    { key: '254', location: 'Europe/Belgrade', timezone: 2, value: '(GMT+02:00) Europe, Belgrade' },
    { key: '255', location: 'Europe/Berlin', timezone: 2, value: '(GMT+02:00) Europe, Berlin' },
    { key: '256', location: 'Europe/Bratislava', timezone: 2, value: '(GMT+02:00) Europe, Bratislava' },
    { key: '257', location: 'Europe/Brussels', timezone: 2, value: '(GMT+02:00) Europe, Brussels' },
    { key: '258', location: 'Europe/Budapest', timezone: 2, value: '(GMT+02:00) Europe, Budapest' },
    { key: '259', location: 'Europe/Busingen', timezone: 2, value: '(GMT+02:00) Europe, Busingen' },
    { key: '260', location: 'Europe/Copenhagen', timezone: 2, value: '(GMT+02:00) Europe, Copenhagen' },
    { key: '261', location: 'Europe/Gibraltar', timezone: 2, value: '(GMT+02:00) Europe, Gibraltar' },
    { key: '262', location: 'Europe/Kaliningrad', timezone: 2, value: '(GMT+02:00) Europe, Kaliningrad' },
    { key: '263', location: 'Europe/Ljubljana', timezone: 2, value: '(GMT+02:00) Europe, Ljubljana' },
    { key: '264', location: 'Europe/Luxembourg', timezone: 2, value: '(GMT+02:00) Europe, Luxembourg' },
    { key: '265', location: 'Europe/Madrid', timezone: 2, value: '(GMT+02:00) Europe, Madrid' },
    { key: '266', location: 'Europe/Malta', timezone: 2, value: '(GMT+02:00) Europe, Malta' },
    { key: '267', location: 'Europe/Monaco', timezone: 2, value: '(GMT+02:00) Europe, Monaco' },
    { key: '268', location: 'Europe/Oslo', timezone: 2, value: '(GMT+02:00) Europe, Oslo' },
    { key: '269', location: 'Europe/Paris', timezone: 2, value: '(GMT+02:00) Europe, Paris' },
    { key: '270', location: 'Europe/Podgorica', timezone: 2, value: '(GMT+02:00) Europe, Podgorica' },
    { key: '271', location: 'Europe/Prague', timezone: 2, value: '(GMT+02:00) Europe, Prague' },
    { key: '272', location: 'Europe/Rome', timezone: 2, value: '(GMT+02:00) Europe, Rome' },
    { key: '273', location: 'Europe/San_Marino', timezone: 2, value: '(GMT+02:00) Europe, San Marino' },
    { key: '274', location: 'Europe/Sarajevo', timezone: 2, value: '(GMT+02:00) Europe, Sarajevo' },
    { key: '275', location: 'Europe/Skopje', timezone: 2, value: '(GMT+02:00) Europe, Skopje' },
    { key: '276', location: 'Europe/Stockholm', timezone: 2, value: '(GMT+02:00) Europe, Stockholm' },
    { key: '277', location: 'Europe/Tirane', timezone: 2, value: '(GMT+02:00) Europe, Tirane' },
    { key: '278', location: 'Europe/Vaduz', timezone: 2, value: '(GMT+02:00) Europe, Vaduz' },
    { key: '279', location: 'Europe/Vatican', timezone: 2, value: '(GMT+02:00) Europe, Vatican' },
    { key: '280', location: 'Europe/Vienna', timezone: 2, value: '(GMT+02:00) Europe, Vienna' },
    { key: '281', location: 'Europe/Warsaw', timezone: 2, value: '(GMT+02:00) Europe, Warsaw' },
    { key: '282', location: 'Europe/Zagreb', timezone: 2, value: '(GMT+02:00) Europe, Zagreb' },
    { key: '283', location: 'Europe/Zurich', timezone: 2, value: '(GMT+02:00) Europe, Zurich' },
    { key: '284', location: 'Libya', timezone: 2, value: '(GMT+02:00) Libya' },
    { key: '285', location: 'MET', timezone: 2, value: '(GMT+02:00) MET' },
    { key: '286', location: 'Poland', timezone: 2, value: '(GMT+02:00) Poland' },
    { key: '287', location: 'Africa/Algiers', timezone: 1, value: '(GMT+01:00) Africa, Algiers' },
    { key: '288', location: 'Africa/Bangui', timezone: 1, value: '(GMT+01:00) Africa, Bangui' },
    { key: '289', location: 'Africa/Brazzaville', timezone: 1, value: '(GMT+01:00) Africa, Brazzaville' },
    { key: '290', location: 'Africa/Casablanca', timezone: 1, value: '(GMT+01:00) Africa, Casablanca' },
    { key: '291', location: 'Africa/Douala', timezone: 1, value: '(GMT+01:00) Africa, Douala' },
    { key: '292', location: 'Africa/El_Aaiun', timezone: 1, value: '(GMT+01:00) Africa, El Aaiun' },
    { key: '293', location: 'Africa/Kinshasa', timezone: 1, value: '(GMT+01:00) Africa, Kinshasa' },
    { key: '294', location: 'Africa/Lagos', timezone: 1, value: '(GMT+01:00) Africa, Lagos' },
    { key: '295', location: 'Africa/Libreville', timezone: 1, value: '(GMT+01:00) Africa, Libreville' },
    { key: '296', location: 'Africa/Luanda', timezone: 1, value: '(GMT+01:00) Africa, Luanda' },
    { key: '297', location: 'Africa/Malabo', timezone: 1, value: '(GMT+01:00) Africa, Malabo' },
    { key: '298', location: 'Africa/Ndjamena', timezone: 1, value: '(GMT+01:00) Africa, Ndjamena' },
    { key: '299', location: 'Africa/Niamey', timezone: 1, value: '(GMT+01:00) Africa, Niamey' },
    { key: '300', location: 'Africa/Porto-Novo', timezone: 1, value: '(GMT+01:00) Africa, Porto-Novo' },
    { key: '301', location: 'Africa/Sao_Tome', timezone: 1, value: '(GMT+01:00) Africa, Sao Tome' },
    { key: '302', location: 'Africa/Tunis', timezone: 1, value: '(GMT+01:00) Africa, Tunis' },
    { key: '303', location: 'Atlantic/Canary', timezone: 1, value: '(GMT+01:00) Atlantic, Canary' },
    { key: '304', location: 'Atlantic/Faeroe', timezone: 1, value: '(GMT+01:00) Atlantic, Faeroe' },
    { key: '305', location: 'Atlantic/Faroe', timezone: 1, value: '(GMT+01:00) Atlantic, Faroe' },
    { key: '306', location: 'Atlantic/Madeira', timezone: 1, value: '(GMT+01:00) Atlantic, Madeira' },
    { key: '307', location: 'Eire', timezone: 1, value: '(GMT+01:00) Eire' },
    { key: '308', location: 'Etc/GMT-1', timezone: 1, value: '(GMT+01:00) Etc, GMT-1' },
    { key: '309', location: 'Europe/Belfast', timezone: 1, value: '(GMT+01:00) Europe, Belfast' },
    { key: '310', location: 'Europe/Dublin', timezone: 1, value: '(GMT+01:00) Europe, Dublin' },
    { key: '311', location: 'Europe/Guernsey', timezone: 1, value: '(GMT+01:00) Europe, Guernsey' },
    { key: '312', location: 'Europe/Isle_of_Man', timezone: 1, value: '(GMT+01:00) Europe, Isle of Man' },
    { key: '313', location: 'Europe/Jersey', timezone: 1, value: '(GMT+01:00) Europe, Jersey' },
    { key: '314', location: 'Europe/Lisbon', timezone: 1, value: '(GMT+01:00) Europe, Lisbon' },
    { key: '315', location: 'Europe/London', timezone: 1, value: '(GMT+01:00) Europe, London' },
    { key: '316', location: 'GB', timezone: 1, value: '(GMT+01:00) GB' },
    { key: '317', location: 'GB-Eire', timezone: 1, value: '(GMT+01:00) GB-Eire' },
    { key: '318', location: 'Portugal', timezone: 1, value: '(GMT+01:00) Portugal' },
    { key: '319', location: 'WET', timezone: 1, value: '(GMT+01:00) WET' },
    { key: '320', location: 'Africa/Abidjan', timezone: 0, value: '(GMT+00:00) Africa, Abidjan' },
    { key: '321', location: 'Africa/Accra', timezone: 0, value: '(GMT+00:00) Africa, Accra' },
    { key: '322', location: 'Africa/Bamako', timezone: 0, value: '(GMT+00:00) Africa, Bamako' },
    { key: '323', location: 'Africa/Banjul', timezone: 0, value: '(GMT+00:00) Africa, Banjul' },
    { key: '324', location: 'Africa/Bissau', timezone: 0, value: '(GMT+00:00) Africa, Bissau' },
    { key: '325', location: 'Africa/Conakry', timezone: 0, value: '(GMT+00:00) Africa, Conakry' },
    { key: '326', location: 'Africa/Dakar', timezone: 0, value: '(GMT+00:00) Africa, Dakar' },
    { key: '327', location: 'Africa/Freetown', timezone: 0, value: '(GMT+00:00) Africa, Freetown' },
    { key: '328', location: 'Africa/Lome', timezone: 0, value: '(GMT+00:00) Africa, Lome' },
    { key: '329', location: 'Africa/Monrovia', timezone: 0, value: '(GMT+00:00) Africa, Monrovia' },
    { key: '330', location: 'Africa/Nouakchott', timezone: 0, value: '(GMT+00:00) Africa, Nouakchott' },
    { key: '331', location: 'Africa/Ouagadougou', timezone: 0, value: '(GMT+00:00) Africa, Ouagadougou' },
    { key: '332', location: 'Africa/Timbuktu', timezone: 0, value: '(GMT+00:00) Africa, Timbuktu' },
    { key: '333', location: 'America/Danmarkshavn', timezone: 0, value: '(GMT+00:00) America, Danmarkshavn' },
    { key: '334', location: 'America/Scoresbysund', timezone: 0, value: '(GMT+00:00) America, Scoresbysund' },
    { key: '335', location: 'Atlantic/Azores', timezone: 0, value: '(GMT+00:00) Atlantic, Azores' },
    { key: '336', location: 'Atlantic/Reykjavik', timezone: 0, value: '(GMT+00:00) Atlantic, Reykjavik' },
    { key: '337', location: 'Atlantic/St_Helena', timezone: 0, value: '(GMT+00:00) Atlantic, St Helena' },
    { key: '338', location: 'Etc/GMT', timezone: 0, value: '(GMT+00:00) Etc, GMT' },
    { key: '339', location: 'Etc/GMT+0', timezone: 0, value: '(GMT+00:00) Etc, GMT+0' },
    { key: '340', location: 'Etc/GMT-0', timezone: 0, value: '(GMT+00:00) Etc, GMT-0' },
    { key: '341', location: 'Etc/GMT0', timezone: 0, value: '(GMT+00:00) Etc, GMT0' },
    { key: '342', location: 'Etc/Greenwich', timezone: 0, value: '(GMT+00:00) Etc, Greenwich' },
    { key: '343', location: 'Etc/UCT', timezone: 0, value: '(GMT+00:00) Etc, UCT' },
    { key: '344', location: 'Etc/Universal', timezone: 0, value: '(GMT+00:00) Etc, Universal' },
    { key: '345', location: 'Etc/UTC', timezone: 0, value: '(GMT+00:00) Etc, UTC' },
    { key: '346', location: 'Etc/Zulu', timezone: 0, value: '(GMT+00:00) Etc, Zulu' },
    { key: '347', location: 'GMT', timezone: 0, value: '(GMT+00:00) GMT' },
    { key: '348', location: 'GMT+0', timezone: 0, value: '(GMT+00:00) GMT+0' },
    { key: '349', location: 'GMT-0', timezone: 0, value: '(GMT+00:00) GMT-0' },
    { key: '350', location: 'GMT0', timezone: 0, value: '(GMT+00:00) GMT0' },
    { key: '351', location: 'Greenwich', timezone: 0, value: '(GMT+00:00) Greenwich' },
    { key: '352', location: 'Iceland', timezone: 0, value: '(GMT+00:00) Iceland' },
    { key: '353', location: 'UCT', timezone: 0, value: '(GMT+00:00) UCT' },
    { key: '354', location: 'Universal', timezone: 0, value: '(GMT+00:00) Universal' },
    { key: '355', location: 'UTC', timezone: 0, value: '(GMT+00:00) UTC' },
    { key: '356', location: 'Zulu', timezone: 0, value: '(GMT+00:00) Zulu' },
    { key: '357', location: 'Atlantic/Cape_Verde', timezone: -1, value: '(GMT-01:00) Atlantic, Cape Verde' },
    { key: '358', location: 'Etc/GMT+1', timezone: -1, value: '(GMT-01:00) Etc, GMT+1' },
    { key: '359', location: 'America/Godthab', timezone: -2, value: '(GMT-02:00) America, Godthab' },
    { key: '360', location: 'America/Miquelon', timezone: -2, value: '(GMT-02:00) America, Miquelon' },
    { key: '361', location: 'America/Noronha', timezone: -2, value: '(GMT-02:00) America, Noronha' },
    { key: '362', location: 'Atlantic/South_Georgia', timezone: -2, value: '(GMT-02:00) Atlantic, South Georgia' },
    { key: '363', location: 'Brazil/DeNoronha', timezone: -2, value: '(GMT-02:00) Brazil, DeNoronha' },
    { key: '364', location: 'Etc/GMT+2', timezone: -2, value: '(GMT-02:00) Etc, GMT+2' },
    { key: '365', location: 'America/St_Johns', timezone: -2.5, value: '(GMT-02:30) America, St Johns' },
    { key: '366', location: 'Canada/Newfoundland', timezone: -2.5, value: '(GMT-02:30) Canada, Newfoundland' },
    { key: '367', location: 'America/Araguaina', timezone: -3, value: '(GMT-03:00) America, Araguaina' },
    { key: '368', location: 'America/Argentina/Buenos_Aires', timezone: -3, value: '(GMT-03:00) America, Argentina, Buenos Aires' },
    { key: '369', location: 'America/Argentina/Catamarca', timezone: -3, value: '(GMT-03:00) America, Argentina, Catamarca' },
    { key: '370', location: 'America/Argentina/ComodRivadavia', timezone: -3, value: '(GMT-03:00) America, Argentina, ComodRivadavia' },
    { key: '371', location: 'America/Argentina/Cordoba', timezone: -3, value: '(GMT-03:00) America, Argentina, Cordoba' },
    { key: '372', location: 'America/Argentina/Jujuy', timezone: -3, value: '(GMT-03:00) America, Argentina, Jujuy' },
    { key: '373', location: 'America/Argentina/La_Rioja', timezone: -3, value: '(GMT-03:00) America, Argentina, La Rioja' },
    { key: '374', location: 'America/Argentina/Mendoza', timezone: -3, value: '(GMT-03:00) America, Argentina, Mendoza' },
    { key: '375', location: 'America/Argentina/Rio_Gallegos', timezone: -3, value: '(GMT-03:00) America, Argentina, Rio Gallegos' },
    { key: '376', location: 'America/Argentina/Salta', timezone: -3, value: '(GMT-03:00) America, Argentina, Salta' },
    { key: '377', location: 'America/Argentina/San_Juan', timezone: -3, value: '(GMT-03:00) America, Argentina, San Juan' },
    { key: '378', location: 'America/Argentina/San_Luis', timezone: -3, value: '(GMT-03:00) America, Argentina, San Luis' },
    { key: '379', location: 'America/Argentina/Tucuman', timezone: -3, value: '(GMT-03:00) America, Argentina, Tucuman' },
    { key: '380', location: 'America/Argentina/Ushuaia', timezone: -3, value: '(GMT-03:00) America, Argentina, Ushuaia' },
    { key: '381', location: 'America/Bahia', timezone: -3, value: '(GMT-03:00) America, Bahia' },
    { key: '382', location: 'America/Belem', timezone: -3, value: '(GMT-03:00) America, Belem' },
    { key: '383', location: 'America/Buenos_Aires', timezone: -3, value: '(GMT-03:00) America, Buenos Aires' },
    { key: '384', location: 'America/Catamarca', timezone: -3, value: '(GMT-03:00) America, Catamarca' },
    { key: '385', location: 'America/Cayenne', timezone: -3, value: '(GMT-03:00) America, Cayenne' },
    { key: '386', location: 'America/Cordoba', timezone: -3, value: '(GMT-03:00) America, Cordoba' },
    { key: '387', location: 'America/Fortaleza', timezone: -3, value: '(GMT-03:00) America, Fortaleza' },
    { key: '388', location: 'America/Glace_Bay', timezone: -3, value: '(GMT-03:00) America, Glace Bay' },
    { key: '389', location: 'America/Goose_Bay', timezone: -3, value: '(GMT-03:00) America, Goose Bay' },
    { key: '390', location: 'America/Halifax', timezone: -3, value: '(GMT-03:00) America, Halifax' },
    { key: '391', location: 'America/Jujuy', timezone: -3, value: '(GMT-03:00) America, Jujuy' },
    { key: '392', location: 'America/Maceio', timezone: -3, value: '(GMT-03:00) America, Maceio' },
    { key: '393', location: 'America/Mendoza', timezone: -3, value: '(GMT-03:00) America, Mendoza' },
    { key: '394', location: 'America/Moncton', timezone: -3, value: '(GMT-03:00) America, Moncton' },
    { key: '395', location: 'America/Montevideo', timezone: -3, value: '(GMT-03:00) America, Montevideo' },
    { key: '396', location: 'America/Paramaribo', timezone: -3, value: '(GMT-03:00) America, Paramaribo' },
    { key: '397', location: 'America/Punta_Arenas', timezone: -3, value: '(GMT-03:00) America, Punta Arenas' },
    { key: '398', location: 'America/Recife', timezone: -3, value: '(GMT-03:00) America, Recife' },
    { key: '399', location: 'America/Rosario', timezone: -3, value: '(GMT-03:00) America, Rosario' },
    { key: '400', location: 'America/Santarem', timezone: -3, value: '(GMT-03:00) America, Santarem' },
    { key: '401', location: 'America/Sao_Paulo', timezone: -3, value: '(GMT-03:00) America, Sao Paulo' },
    { key: '402', location: 'America/Thule', timezone: -3, value: '(GMT-03:00) America, Thule' },
    { key: '403', location: 'Antarctica/Palmer', timezone: -3, value: '(GMT-03:00) Antarctica, Palmer' },
    { key: '404', location: 'Antarctica/Rothera', timezone: -3, value: '(GMT-03:00) Antarctica, Rothera' },
    { key: '405', location: 'Atlantic/Bermuda', timezone: -3, value: '(GMT-03:00) Atlantic, Bermuda' },
    { key: '406', location: 'Atlantic/Stanley', timezone: -3, value: '(GMT-03:00) Atlantic, Stanley' },
    { key: '407', location: 'Brazil/East', timezone: -3, value: '(GMT-03:00) Brazil, East' },
    { key: '408', location: 'Canada/Atlantic', timezone: -3, value: '(GMT-03:00) Canada, Atlantic' },
    { key: '409', location: 'Etc/GMT+3', timezone: -3, value: '(GMT-03:00) Etc, GMT+3' },
    { key: '410', location: 'America/Anguilla', timezone: -4, value: '(GMT-04:00) America, Anguilla' },
    { key: '411', location: 'America/Antigua', timezone: -4, value: '(GMT-04:00) America, Antigua' },
    { key: '412', location: 'America/Aruba', timezone: -4, value: '(GMT-04:00) America, Aruba' },
    { key: '413', location: 'America/Asuncion', timezone: -4, value: '(GMT-04:00) America, Asuncion' },
    { key: '414', location: 'America/Barbados', timezone: -4, value: '(GMT-04:00) America, Barbados' },
    { key: '415', location: 'America/Blanc-Sablon', timezone: -4, value: '(GMT-04:00) America, Blanc-Sablon' },
    { key: '416', location: 'America/Boa_Vista', timezone: -4, value: '(GMT-04:00) America, Boa Vista' },
    { key: '417', location: 'America/Campo_Grande', timezone: -4, value: '(GMT-04:00) America, Campo Grande' },
    { key: '418', location: 'America/Caracas', timezone: -4, value: '(GMT-04:00) America, Caracas' },
    { key: '419', location: 'America/Cuiaba', timezone: -4, value: '(GMT-04:00) America, Cuiaba' },
    { key: '420', location: 'America/Curacao', timezone: -4, value: '(GMT-04:00) America, Curacao' },
    { key: '421', location: 'America/Detroit', timezone: -4, value: '(GMT-04:00) America, Detroit' },
    { key: '422', location: 'America/Dominica', timezone: -4, value: '(GMT-04:00) America, Dominica' },
    { key: '423', location: 'America/Fort_Wayne', timezone: -4, value: '(GMT-04:00) America, Fort Wayne' },
    { key: '424', location: 'America/Grand_Turk', timezone: -4, value: '(GMT-04:00) America, Grand Turk' },
    { key: '425', location: 'America/Grenada', timezone: -4, value: '(GMT-04:00) America, Grenada' },
    { key: '426', location: 'America/Guadeloupe', timezone: -4, value: '(GMT-04:00) America, Guadeloupe' },
    { key: '427', location: 'America/Guyana', timezone: -4, value: '(GMT-04:00) America, Guyana' },
    { key: '428', location: 'America/Havana', timezone: -4, value: '(GMT-04:00) America, Havana' },
    { key: '429', location: 'America/Indiana/Indianapolis', timezone: -4, value: '(GMT-04:00) America, Indiana, Indianapolis' },
    { key: '430', location: 'America/Indiana/Marengo', timezone: -4, value: '(GMT-04:00) America, Indiana, Marengo' },
    { key: '431', location: 'America/Indiana/Petersburg', timezone: -4, value: '(GMT-04:00) America, Indiana, Petersburg' },
    { key: '432', location: 'America/Indiana/Vevay', timezone: -4, value: '(GMT-04:00) America, Indiana, Vevay' },
    { key: '433', location: 'America/Indiana/Vincennes', timezone: -4, value: '(GMT-04:00) America, Indiana, Vincennes' },
    { key: '434', location: 'America/Indiana/Winamac', timezone: -4, value: '(GMT-04:00) America, Indiana, Winamac' },
    { key: '435', location: 'America/Indianapolis', timezone: -4, value: '(GMT-04:00) America, Indianapolis' },
    { key: '436', location: 'America/Iqaluit', timezone: -4, value: '(GMT-04:00) America, Iqaluit' },
    { key: '437', location: 'America/Kentucky/Louisville', timezone: -4, value: '(GMT-04:00) America, Kentucky, Louisville' },
    { key: '438', location: 'America/Kentucky/Monticello', timezone: -4, value: '(GMT-04:00) America, Kentucky, Monticello' },
    { key: '439', location: 'America/Kralendijk', timezone: -4, value: '(GMT-04:00) America, Kralendijk' },
    { key: '440', location: 'America/La_Paz', timezone: -4, value: '(GMT-04:00) America, La Paz' },
    { key: '441', location: 'America/Louisville', timezone: -4, value: '(GMT-04:00) America, Louisville' },
    { key: '442', location: 'America/Lower_Princes', timezone: -4, value: '(GMT-04:00) America, Lower Princes' },
    { key: '443', location: 'America/Manaus', timezone: -4, value: '(GMT-04:00) America, Manaus' },
    { key: '444', location: 'America/Marigot', timezone: -4, value: '(GMT-04:00) America, Marigot' },
    { key: '445', location: 'America/Martinique', timezone: -4, value: '(GMT-04:00) America, Martinique' },
    { key: '446', location: 'America/Montreal', timezone: -4, value: '(GMT-04:00) America, Montreal' },
    { key: '447', location: 'America/Montserrat', timezone: -4, value: '(GMT-04:00) America, Montserrat' },
    { key: '448', location: 'America/Nassau', timezone: -4, value: '(GMT-04:00) America, Nassau' },
    { key: '449', location: 'America/New_York', timezone: -4, value: '(GMT-04:00) America, New York' },
    { key: '450', location: 'America/Nipigon', timezone: -4, value: '(GMT-04:00) America, Nipigon' },
    { key: '451', location: 'America/Pangnirtung', timezone: -4, value: '(GMT-04:00) America, Pangnirtung' },
    { key: '452', location: 'America/Port_of_Spain', timezone: -4, value: '(GMT-04:00) America, Port of Spain' },
    { key: '453', location: 'America/Port-au-Prince', timezone: -4, value: '(GMT-04:00) America, Port-au-Prince' },
    { key: '454', location: 'America/Porto_Velho', timezone: -4, value: '(GMT-04:00) America, Porto Velho' },
    { key: '455', location: 'America/Puerto_Rico', timezone: -4, value: '(GMT-04:00) America, Puerto Rico' },
    { key: '456', location: 'America/Santiago', timezone: -4, value: '(GMT-04:00) America, Santiago' },
    { key: '457', location: 'America/Santo_Domingo', timezone: -4, value: '(GMT-04:00) America, Santo Domingo' },
    { key: '458', location: 'America/St_Barthelemy', timezone: -4, value: '(GMT-04:00) America, St Barthelemy' },
    { key: '459', location: 'America/St_Kitts', timezone: -4, value: '(GMT-04:00) America, St Kitts' },
    { key: '460', location: 'America/St_Lucia', timezone: -4, value: '(GMT-04:00) America, St Lucia' },
    { key: '461', location: 'America/St_Thomas', timezone: -4, value: '(GMT-04:00) America, St Thomas' },
    { key: '462', location: 'America/St_Vincent', timezone: -4, value: '(GMT-04:00) America, St Vincent' },
    { key: '463', location: 'America/Thunder_Bay', timezone: -4, value: '(GMT-04:00) America, Thunder Bay' },
    { key: '464', location: 'America/Toronto', timezone: -4, value: '(GMT-04:00) America, Toronto' },
    { key: '465', location: 'America/Tortola', timezone: -4, value: '(GMT-04:00) America, Tortola' },
    { key: '466', location: 'America/Virgin', timezone: -4, value: '(GMT-04:00) America, Virgin' },
    { key: '467', location: 'Brazil/West', timezone: -4, value: '(GMT-04:00) Brazil, West' },
    { key: '468', location: 'Canada/Eastern', timezone: -4, value: '(GMT-04:00) Canada, Eastern' },
    { key: '469', location: 'Chile/Continental', timezone: -4, value: '(GMT-04:00) Chile, Continental' },
    { key: '470', location: 'Cuba', timezone: -4, value: '(GMT-04:00) Cuba' },
    { key: '471', location: 'EST5EDT', timezone: -4, value: '(GMT-04:00) EST5EDT' },
    { key: '472', location: 'Etc/GMT+4', timezone: -4, value: '(GMT-04:00) Etc, GMT+4' },
    { key: '473', location: 'US/East-Indiana', timezone: -4, value: '(GMT-04:00) US, East-Indiana' },
    { key: '474', location: 'US/Eastern', timezone: -4, value: '(GMT-04:00) US, Eastern' },
    { key: '475', location: 'US/Michigan', timezone: -4, value: '(GMT-04:00) US, Michigan' },
    { key: '476', location: 'America/Atikokan', timezone: -5, value: '(GMT-05:00) America, Atikokan' },
    { key: '477', location: 'America/Bahia_Banderas', timezone: -5, value: '(GMT-05:00) America, Bahia Banderas' },
    { key: '478', location: 'America/Bogota', timezone: -5, value: '(GMT-05:00) America, Bogota' },
    { key: '479', location: 'America/Cancun', timezone: -5, value: '(GMT-05:00) America, Cancun' },
    { key: '480', location: 'America/Cayman', timezone: -5, value: '(GMT-05:00) America, Cayman' },
    { key: '481', location: 'America/Chicago', timezone: -5, value: '(GMT-05:00) America, Chicago' },
    { key: '482', location: 'America/Coral_Harbour', timezone: -5, value: '(GMT-05:00) America, Coral Harbour' },
    { key: '483', location: 'America/Eirunepe', timezone: -5, value: '(GMT-05:00) America, Eirunepe' },
    { key: '484', location: 'America/Guayaquil', timezone: -5, value: '(GMT-05:00) America, Guayaquil' },
    { key: '485', location: 'America/Indiana/Knox', timezone: -5, value: '(GMT-05:00) America, Indiana, Knox' },
    { key: '486', location: 'America/Indiana/Tell_City', timezone: -5, value: '(GMT-05:00) America, Indiana, Tell City' },
    { key: '487', location: 'America/Jamaica', timezone: -5, value: '(GMT-05:00) America, Jamaica' },
    { key: '488', location: 'America/Knox_IN', timezone: -5, value: '(GMT-05:00) America, Knox IN' },
    { key: '489', location: 'America/Lima', timezone: -5, value: '(GMT-05:00) America, Lima' },
    { key: '490', location: 'America/Matamoros', timezone: -5, value: '(GMT-05:00) America, Matamoros' },
    { key: '491', location: 'America/Menominee', timezone: -5, value: '(GMT-05:00) America, Menominee' },
    { key: '492', location: 'America/Merida', timezone: -5, value: '(GMT-05:00) America, Merida' },
    { key: '493', location: 'America/Mexico_City', timezone: -5, value: '(GMT-05:00) America, Mexico City' },
    { key: '494', location: 'America/Monterrey', timezone: -5, value: '(GMT-05:00) America, Monterrey' },
    { key: '495', location: 'America/North_Dakota/Beulah', timezone: -5, value: '(GMT-05:00) America, North Dakota, Beulah' },
    { key: '496', location: 'America/North_Dakota/Center', timezone: -5, value: '(GMT-05:00) America, North Dakota, Center' },
    { key: '497', location: 'America/North_Dakota/New_Salem', timezone: -5, value: '(GMT-05:00) America, North Dakota, New Salem' },
    { key: '498', location: 'America/Panama', timezone: -5, value: '(GMT-05:00) America, Panama' },
    { key: '499', location: 'America/Porto_Acre', timezone: -5, value: '(GMT-05:00) America, Porto Acre' },
    { key: '500', location: 'America/Rainy_River', timezone: -5, value: '(GMT-05:00) America, Rainy River' },
    { key: '501', location: 'America/Rankin_Inlet', timezone: -5, value: '(GMT-05:00) America, Rankin Inlet' },
    { key: '502', location: 'America/Resolute', timezone: -5, value: '(GMT-05:00) America, Resolute' },
    { key: '503', location: 'America/Rio_Branco', timezone: -5, value: '(GMT-05:00) America, Rio Branco' },
    { key: '504', location: 'America/Winnipeg', timezone: -5, value: '(GMT-05:00) America, Winnipeg' },
    { key: '505', location: 'Brazil/Acre', timezone: -5, value: '(GMT-05:00) Brazil, Acre' },
    { key: '506', location: 'Canada/Central', timezone: -5, value: '(GMT-05:00) Canada, Central' },
    { key: '507', location: 'CST6CDT', timezone: -5, value: '(GMT-05:00) CST6CDT' },
    { key: '508', location: 'EST', timezone: -5, value: '(GMT-05:00) EST' },
    { key: '509', location: 'Etc/GMT+5', timezone: -5, value: '(GMT-05:00) Etc, GMT+5' },
    { key: '510', location: 'Jamaica', timezone: -5, value: '(GMT-05:00) Jamaica' },
    { key: '511', location: 'Mexico/General', timezone: -5, value: '(GMT-05:00) Mexico, General' },
    { key: '512', location: 'US/Central', timezone: -5, value: '(GMT-05:00) US, Central' },
    { key: '513', location: 'US/Indiana-Starke', timezone: -5, value: '(GMT-05:00) US, Indiana-Starke' },
    { key: '514', location: 'America/Belize', timezone: -6, value: '(GMT-06:00) America, Belize' },
    { key: '515', location: 'America/Boise', timezone: -6, value: '(GMT-06:00) America, Boise' },
    { key: '516', location: 'America/Cambridge_Bay', timezone: -6, value: '(GMT-06:00) America, Cambridge Bay' },
    { key: '517', location: 'America/Chihuahua', timezone: -6, value: '(GMT-06:00) America, Chihuahua' },
    { key: '518', location: 'America/Costa_Rica', timezone: -6, value: '(GMT-06:00) America, Costa Rica' },
    { key: '519', location: 'America/Denver', timezone: -6, value: '(GMT-06:00) America, Denver' },
    { key: '520', location: 'America/Edmonton', timezone: -6, value: '(GMT-06:00) America, Edmonton' },
    { key: '521', location: 'America/El_Salvador', timezone: -6, value: '(GMT-06:00) America, El Salvador' },
    { key: '522', location: 'America/Guatemala', timezone: -6, value: '(GMT-06:00) America, Guatemala' },
    { key: '523', location: 'America/Inuvik', timezone: -6, value: '(GMT-06:00) America, Inuvik' },
    { key: '524', location: 'America/Managua', timezone: -6, value: '(GMT-06:00) America, Managua' },
    { key: '525', location: 'America/Mazatlan', timezone: -6, value: '(GMT-06:00) America, Mazatlan' },
    { key: '526', location: 'America/Ojinaga', timezone: -6, value: '(GMT-06:00) America, Ojinaga' },
    { key: '527', location: 'America/Regina', timezone: -6, value: '(GMT-06:00) America, Regina' },
    { key: '528', location: 'America/Shiprock', timezone: -6, value: '(GMT-06:00) America, Shiprock' },
    { key: '529', location: 'America/Swift_Current', timezone: -6, value: '(GMT-06:00) America, Swift Current' },
    { key: '530', location: 'America/Tegucigalpa', timezone: -6, value: '(GMT-06:00) America, Tegucigalpa' },
    { key: '531', location: 'America/Yellowknife', timezone: -6, value: '(GMT-06:00) America, Yellowknife' },
    { key: '532', location: 'Canada/Mountain', timezone: -6, value: '(GMT-06:00) Canada, Mountain' },
    { key: '533', location: 'Canada/Saskatchewan', timezone: -6, value: '(GMT-06:00) Canada, Saskatchewan' },
    { key: '534', location: 'Chile/EasterIsland', timezone: -6, value: '(GMT-06:00) Chile, EasterIsland' },
    { key: '535', location: 'Etc/GMT+6', timezone: -6, value: '(GMT-06:00) Etc, GMT+6' },
    { key: '536', location: 'Mexico/BajaSur', timezone: -6, value: '(GMT-06:00) Mexico, BajaSur' },
    { key: '537', location: 'MST7MDT', timezone: -6, value: '(GMT-06:00) MST7MDT' },
    { key: '538', location: 'Navajo', timezone: -6, value: '(GMT-06:00) Navajo' },
    { key: '539', location: 'Pacific/Easter', timezone: -6, value: '(GMT-06:00) Pacific, Easter' },
    { key: '540', location: 'Pacific/Galapagos', timezone: -6, value: '(GMT-06:00) Pacific, Galapagos' },
    { key: '541', location: 'US/Mountain', timezone: -6, value: '(GMT-06:00) US, Mountain' },
    { key: '542', location: 'America/Creston', timezone: -7, value: '(GMT-07:00) America, Creston' },
    { key: '543', location: 'America/Dawson', timezone: -7, value: '(GMT-07:00) America, Dawson' },
    { key: '544', location: 'America/Dawson_Creek', timezone: -7, value: '(GMT-07:00) America, Dawson Creek' },
    { key: '545', location: 'America/Ensenada', timezone: -7, value: '(GMT-07:00) America, Ensenada' },
    { key: '546', location: 'America/Fort_Nelson', timezone: -7, value: '(GMT-07:00) America, Fort Nelson' },
    { key: '547', location: 'America/Hermosillo', timezone: -7, value: '(GMT-07:00) America, Hermosillo' },
    { key: '548', location: 'America/Los_Angeles', timezone: -7, value: '(GMT-07:00) America, Los Angeles' },
    { key: '549', location: 'America/Phoenix', timezone: -7, value: '(GMT-07:00) America, Phoenix' },
    { key: '550', location: 'America/Santa_Isabel', timezone: -7, value: '(GMT-07:00) America, Santa Isabel' },
    { key: '551', location: 'America/Tijuana', timezone: -7, value: '(GMT-07:00) America, Tijuana' },
    { key: '552', location: 'America/Vancouver', timezone: -7, value: '(GMT-07:00) America, Vancouver' },
    { key: '553', location: 'America/Whitehorse', timezone: -7, value: '(GMT-07:00) America, Whitehorse' },
    { key: '554', location: 'Canada/Pacific', timezone: -7, value: '(GMT-07:00) Canada, Pacific' },
    { key: '555', location: 'Canada/Yukon', timezone: -7, value: '(GMT-07:00) Canada, Yukon' },
    { key: '556', location: 'Etc/GMT+7', timezone: -7, value: '(GMT-07:00) Etc, GMT+7' },
    { key: '557', location: 'Mexico/BajaNorte', timezone: -7, value: '(GMT-07:00) Mexico, BajaNorte' },
    { key: '558', location: 'MST', timezone: -7, value: '(GMT-07:00) MST' },
    { key: '559', location: 'PST8PDT', timezone: -7, value: '(GMT-07:00) PST8PDT' },
    { key: '560', location: 'US/Arizona', timezone: -7, value: '(GMT-07:00) US, Arizona' },
    { key: '561', location: 'US/Pacific', timezone: -7, value: '(GMT-07:00) US, Pacific' },
    { key: '562', location: 'US/Pacific-New', timezone: -7, value: '(GMT-07:00) US, Pacific-New' },
    { key: '563', location: 'America/Anchorage', timezone: -8, value: '(GMT-08:00) America, Anchorage' },
    { key: '564', location: 'America/Juneau', timezone: -8, value: '(GMT-08:00) America, Juneau' },
    { key: '565', location: 'America/Metlakatla', timezone: -8, value: '(GMT-08:00) America, Metlakatla' },
    { key: '566', location: 'America/Nome', timezone: -8, value: '(GMT-08:00) America, Nome' },
    { key: '567', location: 'America/Sitka', timezone: -8, value: '(GMT-08:00) America, Sitka' },
    { key: '568', location: 'America/Yakutat', timezone: -8, value: '(GMT-08:00) America, Yakutat' },
    { key: '569', location: 'Etc/GMT+8', timezone: -8, value: '(GMT-08:00) Etc, GMT+8' },
    { key: '570', location: 'Pacific/Pitcairn', timezone: -8, value: '(GMT-08:00) Pacific, Pitcairn' },
    { key: '571', location: 'US/Alaska', timezone: -8, value: '(GMT-08:00) US, Alaska' },
    { key: '572', location: 'America/Adak', timezone: -9, value: '(GMT-09:00) America, Adak' },
    { key: '573', location: 'America/Atka', timezone: -9, value: '(GMT-09:00) America, Atka' },
    { key: '574', location: 'Etc/GMT+9', timezone: -9, value: '(GMT-09:00) Etc, GMT+9' },
    { key: '575', location: 'Pacific/Gambier', timezone: -9, value: '(GMT-09:00) Pacific, Gambier' },
    { key: '576', location: 'US/Aleutian', timezone: -9, value: '(GMT-09:00) US, Aleutian' },
    { key: '577', location: 'Pacific/Marquesas', timezone: -9.5, value: '(GMT-09:30) Pacific, Marquesas' },
    { key: '578', location: 'Etc/GMT+10', timezone: -10, value: '(GMT-10:00) Etc, GMT+10' },
    { key: '579', location: 'HST', timezone: -10, value: '(GMT-10:00) HST' },
    { key: '580', location: 'Pacific/Honolulu', timezone: -10, value: '(GMT-10:00) Pacific, Honolulu' },
    { key: '581', location: 'Pacific/Johnston', timezone: -10, value: '(GMT-10:00) Pacific, Johnston' },
    { key: '582', location: 'Pacific/Rarotonga', timezone: -10, value: '(GMT-10:00) Pacific, Rarotonga' },
    { key: '584', location: 'US/Hawaii', timezone: -10, value: '(GMT-10:00) US, Hawaii' },
    { key: '583', location: 'Pacific/Tahiti', timezone: -10, value: '(GMT-10:00) Pacific, Tahiti' },
    { key: '585', location: 'Etc/GMT+11', timezone: -11, value: '(GMT-11:00) Etc, GMT+11' },
    { key: '586', location: 'Pacific/Midway', timezone: -11, value: '(GMT-11:00) Pacific, Midway' },
    { key: '587', location: 'Pacific/Niue', timezone: -11, value: '(GMT-11:00) Pacific, Niue' },
    { key: '588', location: 'Pacific/Pago_Pago', timezone: -11, value: '(GMT-11:00) Pacific, Pago Pago' },
    { key: '589', location: 'Pacific/Samoa', timezone: -11, value: '(GMT-11:00) Pacific, Samoa' },
    { key: '590', location: 'US/Samoa', timezone: -11, value: '(GMT-11:00) US, Samoa' },
    { key: '591', location: 'Etc/GMT+12', timezone: -12, value: '(GMT-12:00) Etc, GMT+12' }
]
