export default {
	WATCHLIST: 'WATCHLIST',
	ADD_WATCHLIST: 'ADD_WATCHLIST',
	EDIT_WATCHLIST: 'EDIT_WATCHLIST',
	SELECT_WATCHLIST: 'SELECT_WATCHLIST',
	CREATE_WATCHLIST: 'CREATE_WATCHLIST',
	CATEGORIES_WATCHLIST: 'CATEGORIES_WATCHLIST',
	SEARCH_WATCHLIST: 'SEARCH_WATCHLIST',
	SEARCH_PRIBOARD: 'SEARCH_PRIBOARD'
};
