export default {
    CONFIRM_PLACE_ORDER_CHANGE_LOADING_BUTTON_CONFIRM: 'CONFIRM_PLACE_ORDER_CHANGE_LOADING_BUTTON_CONFIRM',
    CONFIRM_PLACE_ORDER_RESET_STATE: 'CONFIRM_PLACE_ORDER_RESET_STATE',
    CONFIRM_PLACE_ORDER_CHANGE_LOADING_INITIAL_MARGIN: 'CONFIRM_PLACE_ORDER_CHANGE_LOADING_INITIAL_MARGIN',
    DISMISS_MODAL_PLACE_ORDER: 'DISMISS_MODAL_PLACE_ORDER'
}
