export const TYPE_ERROR_SYSTEM = {
    RETRY_FAIL_AND_POP_BACK_LOGIN: 'RETRY_FAIL_AND_POP_BACK_LOGIN', // Show Message -> reCall 3 attempt ->show popup
    RETRY_FAIL_AND_CHANGE_UI: 'RETRY_FAIL_AND_CHANGE_UI', // Show Message -> reCall 3 attempt ->change ui message
    SHOW_AUTO_HIDE: 'SHOW_AUTO_HIDE', // Show Message -> 10s auto hide
    SHOW_POPUP: 'SHOW_POPUP', // Show popup force logout
    HIDE: 'HIDE', // khong hien thi ma loi
    RETRY_FAIL_AND_INFINITED: 'RETRY_FAIL_AND_INFINITED' // Show message -> recall không giới sau mỗi 30 đếm ngược
}
export const ERROR_SYSTEM = {
    25001: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25002: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25003: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25004: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25006: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_CHANGE_UI,
    25007: TYPE_ERROR_SYSTEM.SHOW_AUTO_HIDE,
    25009: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_CHANGE_UI,
    25010: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25011: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_CHANGE_UI,
    25012: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_CHANGE_UI,
    25013: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25014: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25015: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25016: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25017: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25018: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25019: TYPE_ERROR_SYSTEM.SHOW_AUTO_HIDE,
    25020: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25021: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25022: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25023: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25024: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25025: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25026: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25027: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25028: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    25031: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    25032: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_INFINITED,
    25033: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_CHANGE_UI,
    25035: TYPE_ERROR_SYSTEM.RETRY_FAIL_AND_POP_BACK_LOGIN,
    666: TYPE_ERROR_SYSTEM.SHOW_POPUP,
    8999: TYPE_ERROR_SYSTEM.SHOW_POPUP

}
export const TIME_DELAYED = 30
export const MAX_NUM_RETRY = 3
