export default {
    ADD_SYMBOL_CHANGE_LOADING: 'ADD_SYMBOL_CHANGE_LOADING',
    ADD_SYMBOL_CHANGE_TEXT: 'ADD_SYMBOL_CHANGE_TEXT',
    ADD_SYMBOL_CHANGE_DIC_SELECTED_SYMBOL: 'ADD_SYMBOL_CHANGE_DIC_SELECTED_SYMBOL',
    ADD_SYMBOL_CHANGE_CLASS_FITLER: 'ADD_SYMBOL_CHANGE_CLASS_FITLER',
    ADD_SYMBOL_INIT_DIC_SELECTED_SYMBOL: 'ADD_SYMBOL_INIT_DIC_SELECTED_SYMBOL'
}
