export default {
	NEW_ORDER_CHANGE_LOADING_BOX_ACCOUNT:
		'NEW_ORDER_CHANGE_LOADING_BOX_ACCOUNT',
	NEW_ORDER_UPDATE_STATE: 'NEW_ORDER_UPDATE_STATE',
	NEW_ORDER_CHANGE_ORDER_TYPE: 'NEW_ORDER_CHANGE_ORDER_TYPE',
	NEW_ORDER_CHANGE_ORDER_TYPE_SL: 'NEW_ORDER_CHANGE_ORDER_TYPE_SL',
	NEW_ORDER_CHANGE_ORDER_TYPE_TP: 'NEW_ORDER_CHANGE_ORDER_TYPE_TP',
	NEW_ORDER_CHANGE_INPUT_TEXT: 'NEW_ORDER_CHANGE_INPUT_TEXT',
	NEW_ORDER_TOGGLE_IGNORE_TYPE: 'NEW_ORDER_TOGGLE_IGNORE_TYPE',
	NEW_ORDER_CHANGE_ORDER_TYPE_OBJECT: 'NEW_ORDER_CHANGE_ORDER_TYPE_OBJECT',
	NEW_ORDER_UPDATE_CURRENT_INPUT_SHOWN: 'NEW_ORDER_UPDATE_CURRENT_INPUT_SHOWN',
	NEW_ORDER_CHANGE_DURATION: 'NEW_ORDER_CHANGE_DURATION',
	NEW_ORDER_CHANGE_DURATION_SL: 'NEW_ORDER_CHANGE_DURATION_SL',
	NEW_ORDER_CHANGE_DURATION_TP: 'NEW_ORDER_CHANGE_DURATION_TP',
	NEW_ORDER_CHANGE_BUY_SELL: 'NEW_ORDER_CHANGE_BUY_SELL',
	NEW_ORDER_CHANGE_SYMBOL_EXCHANGE: 'NEW_ORDER_CHANGE_SYMBOL_EXCHANGE',
	NEW_ORDER_CHANGE_QUANTITY: 'NEW_ORDER_CHANGE_QUANTITY',
	NEW_ORDER_CHANGE_PRICE: 'NEW_ORDER_CHANGE_PRICE',
	NEW_ORDER_CHANGE_LIMIT_PRICE: 'NEW_ORDER_CHANGE_LIMIT_PRICE',
	NEW_ORDER_CHANGE_LIMIT_PRICE_SL: 'NEW_ORDER_CHANGE_LIMIT_PRICE_SL',
	NEW_ORDER_CHANGE_LIMIT_PRICE_TP: 'NEW_ORDER_CHANGE_LIMIT_PRICE_TP',
	NEW_ORDER_CHANGE_DESTINATION: 'NEW_ORDER_CHANGE_DESTINATION',
	NEW_ORDER_CHANGE_DATE_PERIOD: 'NEW_ORDER_CHANGE_DATE_PERIOD',
	NEW_ORDER_CHANGE_DATE_PERIOD_SL: 'NEW_ORDER_CHANGE_DATE_PERIOD_SL',
	NEW_ORDER_CHANGE_DATE_PERIOD_TP: 'NEW_ORDER_CHANGE_DATE_PERIOD_TP',
	NEW_ORDER_CHANGE_TEXT_SEARCH: 'NEW_ORDER_CHANGE_TEXT_SEARCH',
	NEW_ORDER_CHANGE_LOADING: 'NEW_ORDER_CHANGE_LOADING',
	NEW_ORDER_CHANGE_LOADING_SEARCH: 'NEW_ORDER_CHANGE_LOADING_SEARCH',
	NEW_ORDER_CHANGE_LOADING_CHECK_VETTING:
		'NEW_ORDER_CHANGE_LOADING_CHECK_VETTING',
	NEW_ORDER_RESET_STATE: 'NEW_ORDER_RESET_STATE',
	NEW_ORDER_RESET_OBJECT_ORDER: 'NEW_ORDER_RESET_OBJECT_ORDER',
	NEW_ORDER_CHANGE_POSITION_AFFECTED: 'NEW_ORDER_CHANGE_POSITION_AFFECTED',
	NEW_ORDER_CHANGE_LAYOUT: 'NEW_ORDER_CHANGE_LAYOUT',
	NEW_ORDER_TOGGLE_CONTINGENT: 'NEW_ORDER_TOGGLE_CONTINGENT',
	NEW_ORDER_TOGGLE_CONTINGENT_BLOCK: 'NEW_ORDER_TOGGLE_CONTINGENT_BLOCK',
	NEW_ORDER_SET_TEMPLATE_PRICE_POINT_VALUE: 'NEW_ORDER_SET_TEMPLATE_PRICE_POINT_VALUE',
	NEW_ORDER_CHANGE_LOADING_ORDER_ATTRIBUTE:
		'NEW_ORDER_CHANGE_LOADING_ORDER_ATTRIBUTE',
	NEW_ORDER_CHANGE_FOCUS_INPUT: 'NEW_ORDER_CHANGE_FOCUS_INPUT',
	NEW_ORDER_CHANGE_TYPE_INPUT_ORDER_VALUE_VOLUME:
		'NEW_ORDER_CHANGE_TYPE_INPUT_ORDER_VALUE_VOLUME',
	NEW_ORDER_CHANGE_TYPE_INPUT_STOP_PRICE:
		'NEW_ORDER_CHANGE_TYPE_INPUT_STOP_PRICE',
	NEW_ORDER_CHANGE_ORDER_VALUE: 'NEW_ORDER_CHANGE_ORDER_VALUE',
	NEW_ORDER_CHANGE_TYPE_INPUT_TAKE_PROFIT_LOSS:
		'NEW_ORDER_CHANGE_TYPE_INPUT_TAKE_PROFIT_LOSS',
	NEW_ORDER_CHANGE_STOP_PRICE: 'NEW_ORDER_CHANGE_STOP_PRICE',
	NEW_ORDER_CHANGE_TAKE_PROFIT_LOSS: 'NEW_ORDER_CHANGE_TAKE_PROFIT_LOSS',
	NEW_ORDER_CHANGE_BUY_SELL_AND_POSITION_AFFECTED:
		'NEW_ORDER_CHANGE_BUY_SELL_AND_POSITION_AFFECTED',
	NEW_ORDER_INIT_STORE: 'NEW_ORDER_INIT_STORE',
	NEW_ORDER_CHANGE_DISABLED_BUTTON_CONFIRM:
		'NEW_ORDER_CHANGE_DISABLED_BUTTON_CONFIRM',
	NEW_ORDER_CHANGE_STEP_QUANTITY: 'NEW_ORDER_CHANGE_STEP_QUANTITY',
	NEW_ORDER_CHANGE_STEP_ORDER_VALUE: 'NEW_ORDER_CHANGE_STEP_ORDER_VALUE',
	NEW_ORDER_RESET_STATE_WHEN_CHANGE_ACCOUNT:
		'NEW_ORDER_RESET_STATE_WHEN_CHANGE_ACCOUNT',
	NEW_ORDER_GET_ATTRIBUTE: 'NEW_ORDER_GET_ATTRIBUTE',
	NEW_ORDER_CONTIGENT_TYPE: 'NEW_ORDER_CONTIGENT_TYPE',
	NEW_ORDER_CALCULATE_TRIGGER_PRICE: 'NEW_ORDER_CALCULATE_TRIGGER_PRICE',
	NEW_ORDER_SET_TRIGGER_PRICE: 'NEW_ORDER_SET_TRIGGER_PRICE'
};
