export default {
    SEARCH_ACCOUNT_CHANGE_LOADING: 'SEARCH_ACCOUNT_CHANGE_LOADING',
    SEARCH_ACCOUNT_CHANGE_TEXT: 'SEARCH_ACCOUNT_CHANGE_TEXT',
    SEARCH_ACCOUNT_CHANGE_IS_SEARCH: 'SEARCH_ACCOUNT_CHANGE_IS_SEARCH',
    SEARCH_ACCOUNT_HANDLE_SEARCH: 'SEARCH_ACCOUNT_HANDLE_SEARCH'
}
