export default {
    UPDATE_SELECTED: 'EDITWATCH#UPDATE_SELECTED',
    UPDATE_TOP_INDEX: 'EDITWATCH#UPDATE_TOP_INDEX',
    UPDATE_PRICEBOARD: 'EDITWATCH#UPDATE_PRICEBOARD',
    UPDATE_LIST_SYMBOL: 'EDITWATCH#UPDATE_LIST_SYMBOL',
    UPDATE_LIST_SYMBOL_BY_DELETE: 'EDITWATCH#UPDATE_LIST_SYMBOL_BY_DELETE',
    INITIAL_STATE: 'EDITWATCH#INITIAL_STATE',
    RESET_STATE: 'EDITWATCH#RESET_STATE'
}
