export default {
    SEARCH_SYMBOL_CHANGE_LOADING: 'SEARCH_SYMBOL_CHANGE_LOADING',
    SEARCH_SYMBOL_CHANGE_TEXT: 'SEARCH_SYMBOL_CHANGE_TEXT',
    SEARCH_SYMBOL_CHANGE_CLASS_FITLER: 'SEARCH_SYMBOL_CHANGE_CLASS_FITLER',
    SEARCH_SYMBOL_RESET: 'SEARCH_SYMBOL_RESET'
}
