const Constans = {
    CHANGE_SCREEN_ACTIVE: 'CHANGE_SCREEN_ACTIVE_ALERT',
    UPDATE_STATUS_BUTTON_CONFIRM: 'UPDATE_STATUS_BUTTON_CONFIRM',
    ALERT_SET_LOADING: 'ALERT_SET_LOADING',
    EDIT_ALERT_LIST_SET_LOADING: 'EDIT_ALERT_LIST_SET_LOADING'
}
export default Constans
